### ISSUE TITLE
docs: Make CONTRIBUTING.md 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#10]
## Description
Add the contributing guidelines in a folder(CONTRIBUTING.md)

## Status
Approval of two mentors.

**Comment by 96RadhikaJadhav** [comment]
@khushishikhu Can I work on it?

**Comment by vismitap** [comment]
May I work on this as a part of GSSoC'21 ?

**Comment by khushishikhu** [comment]
> May I work on this as a part of GSSoC'21 ?

@vismitap actually the coding period has not been started yet. From 8th March onwards the mentors will happily assign you to the issue.

**Comment by khushishikhu** [comment]
@vismitap assigning this to you. Happy Coding!!

**Comment by vismitap** [comment]
@khushishikhu Do you have any reference CONTRIBUTING.md file you would like me to duplicate?

**Comment by khushishikhu** [comment]
@vismitap Not to duplicate. but You can take reference from the README.md of the project. and then make the PR

**Comment by i-aayush711** [comment]
Can there be multiple assignees? I would like to work on it

**Comment by vismitap** [comment]
Hey @khushishikhu ! Why is the `CONTRIBUTING.md` inside the `.github` directory? Can it not be in the `root` directory? The `.github` can be used for PR/ Issue templates right? Should I move the `CONTRIBUTING.md` in the `root` directory ?

**Comment by khushishikhu** [comment]
@vismitap move CONTRIBUTING.md into root directory ( .gitHub) where issue/PR template are there.

**Comment by vismitap** [comment]
> @vismitap move CONTRIBUTING.md into root directory ( .gitHub) where issue/PR template are there.

It is already in `.github`. Should I move it outside and keep it the README.md?
![image](https://user-images.githubusercontent.com/47056243/110967583-8d048880-837c-11eb-8f54-f7f79b1b40a7.png)
This is the current folder structure.
