### ISSUE TITLE
Dynamic contributors section in README

### ISSUE THREAD

**Issue by SandeepKrSuman** [Feminine-Divine/periodo#100]
## Is your feature request related to a problem? Please describe.
Previously the contributors were supposed to enter their name in readme before creating a pr. This used to create merge conflicts. Although the contributors section is now removed from README can we put it back at the bottom of the readme but this time let it be dynamic so that it is updated automatically?

## Describe the solution you'd like
We can use the github's api for fetching the list of contributors and put it in our README.

## Additional context
The README will look somewhat like this : 
![Screenshot (256)](https://user-images.githubusercontent.com/54541515/111259293-a0e21000-8644-11eb-90bd-4795d5ee99a6.png)

---
If this feature looks relevant assign this issue to me under GSSOC21. Thankyou.

**Comment by khushishikhu** [comment]
@SandeepKrSuman  I don't think that there is a need to have a particular section for contributors in Readme . As we can still see the contributors . So closing this issue. If you have any other idea you can come with that ✌️
