### ISSUE TITLE
display of the prior periods or delayed periods graph

### ISSUE THREAD

**Issue by satavshreya** [Feminine-Divine/periodo#101]
a graph must be there in  order to examine periods timings whether they are on average or super delayed @khushishikhu do let me what do you think of this if yes then do assign me this one! :)

**Comment by khushishikhu** [comment]
@satavshreya where on the website you are planning to add this feature?. I like your idea👍

**Comment by satavshreya** [comment]
Like if a female signs in then there has to be an option at the navbar or just on the homepage "My Track" or something similar that will help her analyse how regular or irregular dates she has had so a pictorial representation would help. : ) @khushishikhu

**Comment by khushishikhu** [comment]
@satavshreya Got it👍🎉. Thank you for opening this issue. Assigning this to you

**Comment by satavshreya** [comment]
Yes, Thank  you!

**Comment by subhangi2731** [comment]
@khushishikhu please assign me this issue. I want to work on this

**Comment by khushishikhu** [comment]
@subhangi2731 assigned you on this
