### ISSUE TITLE
PR deployment from netlify

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#108]
## Is your feature request related to a problem? Please describe.

Maintainer and contributor have to setup the branch in their local to test out and review the PR , which is very time consuming for both contributors and maintainers.
## Describe the solution you'd like

Temporarily deploy the PR from GitHub actions using netlify deploy.

## Additional context

Please read [this](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/#:~:text=Deploy%20Previews%20work%20by%20deploying,branch%20and%20deployed%20to%20production.) for further details on Deployment.

**Comment by vismitap** [comment]
Hey! I would like to work on this issue as a part of GSSoC'21! Please assign me this issue! 🤩

**Comment by mdPial** [comment]
If no one is assigned I would like to work on that issue. I have not assigned in any issue currently.

**Comment by khushishikhu** [comment]
@vismitap Assigning this to you. Happy coding!!
