### ISSUE TITLE
docs: Add the Demo video link in README.md

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#11]
## Description 
Add the demo video link in the README.md of the project. which is uploaded already in the google drive of girlscript.

**Comment by Shwetang550** [comment]
I can do this... Please assign this to me as a GSSoC'21 participant :)

**Comment by khushishikhu** [comment]
@Shwetang550 you can only get assigned to one issue at a time. This is to maintain the decorum. Do ask again when you are done with the previous issue

**Comment by SandeepKrSuman** [comment]
Hey @khushishikhu  Can I work on this under GSSoC'21 ?

**Comment by SandeepKrSuman** [comment]
Hey @khushishikhu can you please assign this to me?

**Comment by khushishikhu** [comment]
@SandeepKrSuman Sure, Assigning this to you. Happy Coding!!

**Comment by SandeepKrSuman** [comment]
Thank you :)
