### ISSUE TITLE
Can we use docker as an Alternative way to Setup Project !

### ISSUE THREAD

**Issue by jain-rishabh-21** [Feminine-Divine/periodo#110]
## Is your feature request related to a problem? Please describe.
Will ease the process of installation for people working on OS different than Linux

## Describe the solution you'd like
Using Docker to use a single command to install

## Additional context
NA

**Comment by jain-rishabh-21** [comment]
If found useful please assign it to me.
Discord: krackerzzz#4371

**Comment by Aaishpra** [comment]
@jain-rishabh-21 assigning you
