### ISSUE TITLE
Design: change card colour

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#113]
## Is your feature request related to a problem? Please describe.

Change the colour of cards in about page to some what light colour

## Additional context

Please do add the screenshot

**Comment by akshitakanojia** [comment]
Hi @khushishikhu,

Will this work

![Screenshot 2021-03-20 232359](https://user-images.githubusercontent.com/44370673/111880795-81940b80-89d3-11eb-84c5-4eecf80dc2ab.jpg)

**Comment by khushishikhu** [comment]
@akshitakanojia  could you make it more light in this tone only

**Comment by akshitakanojia** [comment]
@khushishikhu  have a look at these 

![Screenshot 2021-03-20 233842](https://user-images.githubusercontent.com/44370673/111881309-e05a8480-89d5-11eb-9cb2-db97cd2c8c6e.jpg)

![Screenshot 2021-03-20 234015](https://user-images.githubusercontent.com/44370673/111881320-ea7c8300-89d5-11eb-9e38-fe61ff54aa2b.jpg)

**Comment by khushishikhu** [comment]
@akshitakanojia Looks good now👍. Please go ahead for the PR of it
