### ISSUE TITLE
bug: Adjust

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#117]
**Describe the bug**

Adjust the Navbar and the area where "how we help" is written as currently it is overlapping

**To Reproduce**
1. Go to 'About Us'
2. See error

**Expected behavior**

Overlapping should not be there

**Screenshots**

![image](https://user-images.githubusercontent.com/65439761/111907898-2f0f2980-8a7d-11eb-9bb7-952715246d74.png)

**Desktop (please complete the following information):**

**Comment by Sukriti-sood** [comment]
@khushishikhu Please assign this to me

**Comment by khushishikhu** [comment]
@Sukriti-sood assigned this to you. Happy Coding!!

**Comment by Sukriti-sood** [comment]
@khushishikhu  I also found that it is not responsive for screen size less than 1000

**Comment by khushishikhu** [comment]
@Sukriti-sood you can make a new issue for this after completing this one. Which will also help you to gain more points

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood you can make a new issue for this after completing this one. Which will also help you to gain more points

Please See this Screenshot ,I think overlapping has been fixed

![screencapture-localhost-3000-about-2021-03-22-22_24_55](https://user-images.githubusercontent.com/55010599/112027804-8f759800-8b5d-11eb-9ac5-68c049680079.png)

**Comment by Mukta-Sawant** [comment]
@khushishikhu I would like to work on this as a part of GSSOC'21. Please assign it to me.
