### ISSUE TITLE
Enhancement - Making the Navbar Sticky

### ISSUE THREAD

**Issue by A-HK** [Feminine-Divine/periodo#128]
When you scroll down a page, it would be ideal for the Navbar to still be displayed at the top.

**To Reproduce**
1.Go to AboutUs page or Tips page
2.While scrolling down, the navbar remains at its original position and the user needs to scroll up again to access the page links.

Although this is a relatively trivial issue, I think it would still play a small part in enhancing your website.
If you think this issue is valid, please assign it to me under GSSoc-21!

**Comment by Aaishpra** [comment]
@A-HK issue confirmed and assigned

**Comment by A-HK** [comment]
Made a PR for the same.
