### ISSUE TITLE
Enhancement - Improving GynacHelp form UI

### ISSUE THREAD

**Issue by Rohit-Parameswaran** [Feminine-Divine/periodo#129]
**Description**

- The GynacHelp form UI has scope for improvement. I feel like it can be made a bit more aesthetic and intuitive. 

**Intended enhancements**

- Make changes to form UI - alignment, positioning, making the "Return Home" a button etc.

**Comment by Aaishpra** [comment]
Yep sure thanks for the issue @Rohit-Parameswaran , but please share the design here in the comments before opening a Pull Request
