### ISSUE TITLE
Coding: Create a "Tips" page 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#13]
## Description
Create a page name as "Tips" which needs to be hovered from navbar and design it a bit according to your perspective.

## To merge
Approval by two mentor.

**Comment by kunal299** [comment]
@khushishikhu Could you plz assign this issue to me as a part of Gssoc'21?

**Comment by khushishikhu** [comment]
@kunal299 sure. Assigning this to you

**Comment by kunal299** [comment]
@khushishikhu But my coding period starts from 8th march.

**Comment by kunal299** [comment]
@khushishikhu will it be ok if I work on this issue when the coding period begins.

**Comment by khushishikhu** [comment]
> @khushishikhu will it be ok if I work on this issue when the coding period begins.

Sure then you can start from when the coding period begins

**Comment by khushishikhu** [comment]
@kunal299 when the project mentors will get finalized then I can assign you to any particular issu. Till then research about the project's issues😊

**Comment by Devenkapoor7303** [comment]
Can I work on this issue as a part of GSSOC 2021

**Comment by khushishikhu** [comment]
@Devenkapoor7303 assigning it to you. Happy Coding!!

**Comment by kunal299** [comment]
@khushishikhu Hey, I am working on this issue already.

**Comment by khushishikhu** [comment]
@kunal299 I have already assigned you in one issue. And to maintain the decorum, one can only be assigned to one issue at a time. So the others also get the chance to contribute. If @Devenkapoor7303 is unable to give any update within 3 days then I can assign to you. Hope you got it. Till then Happy Coding ☺️

**Comment by Devenkapoor7303** [comment]
@khushishikhu Yeah I will start working on this issue from today onwards

**Comment by Devenkapoor7303** [comment]
There is one Doubt when I was creating the tips page I noticed that the background image is disturbing the responsiveness of website so do you want to stay it as it is??



![Capture](https://user-images.githubusercontent.com/73438023/110362465-28e96980-7ff6-11eb-98ac-1e9ed57485a5.PNG)

**Comment by khushishikhu** [comment]
@Devenkapoor7303 stay as it is, we will work on this issue too later on

**Comment by Devenkapoor7303** [comment]
Okay @khushishikhu

**Comment by Devenkapoor7303** [comment]
Hello @khushishikhu  I have created the tips page can u review it so that i can make a PR .

I have added the tips in the form of card and u can check it with some CSS

![Capture](https://user-images.githubusercontent.com/73438023/110436505-296f1800-8069-11eb-8839-4454cd31fb4d.PNG)

And then u can add those Tips after deciding what u want to add.

**Comment by khushishikhu** [comment]
@Devenkapoor7303 It looks good to me😍!! Please make a PR for it. Thank you for your efforts!!
