### ISSUE TITLE
Fixing submission of empty notes

### ISSUE THREAD

**Issue by pm0824** [Feminine-Divine/periodo#131]
**Describe the bug**
In notes section, empty notes are getting created. We can obligate the user to complete the note before submitting it.

**To Reproduce**
1. Go to 'notes'
2. Click on 'submit' without filling title and content
3. See error (Empty note created)

**Expected behavior**
Notes should be created only when user fills all the data.

**Screenshots**
![image](https://user-images.githubusercontent.com/46194962/112267335-4cb9da00-8c9b-11eb-87da-2a8b33c1af1e.png)

I am GSSoC'21 participant and would like to contribute to this project. Kindly assign this issue to me.

**Comment by Aaishpra** [comment]
Issue confirmed and assigned

**Comment by pm0824** [comment]
Thank You
