### ISSUE TITLE
Making Images in AboutUs page responsive

### ISSUE THREAD

**Issue by A-HK** [Feminine-Divine/periodo#135]
**Describe the bug**

When the screen is minimized to width < 920 pixels, the images on the About page do not move with the screen, instead staying fixed in their position. Thus, they are not responsive.

**To Reproduce**
1. Go to 'AboutUs' page.
2. Minimize the screen width to less than 920 pixels.
3. See error of images staying fixed on the screen and not moving with the cards.

**Expected behavior**

I would like to fix this error by using CSS media queries to clearly specify behaviour for each screen size range. This would make the image positions behave ideally.

**Screenshots**

- For Screen Size > 920px
![920px_SS](https://user-images.githubusercontent.com/73497800/112438943-84de1d00-8d6e-11eb-9236-d4b00decef31.png)

- For Screen Size < 920px
![less_than_920_px_SS](https://user-images.githubusercontent.com/73497800/112438993-958e9300-8d6e-11eb-930c-7a9179125b5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

Since I have worked on the AboutUs page previously, I would like to ensure that there are no problems from my end and fix the errors that have arisen in this page to make it behave satisfactorily for your website.

If you find this  issue relevant, please assign it to me under GSSoc'21 !

**Comment by khushishikhu** [comment]
@A-HK  thank you so much for opening this issue. Assigning this to you

**Comment by A-HK** [comment]
Made a PR for the same.
Please let me know if everything is satisfactory!
