### ISSUE TITLE
bug: Add the button

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#136]
**Describe the bug**

add the Login button on the navbar. the file is already there in the Pages folder name as "LoginPage" 

**Screenshots**

![image](https://user-images.githubusercontent.com/65439761/112448666-a5ab7000-8d78-11eb-8fea-16b1d5a01778.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by khushishikhu** [comment]
@vismitap assigning this issue to you as it is a for beginner. And our moto for Gssoc is to make every one learn how to work with github

**Comment by Ayush0730** [comment]
Can I work on this issue as a part of GSSoC'21 ?

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?  i will fix this.

**Comment by likhitha-19** [comment]
can i work on this as part of Gssoc

**Comment by vismitap** [comment]
@khushishikhu The navbar is already added! I didn't get what do you want me to do 🤔.
![image](https://user-images.githubusercontent.com/47056243/112730204-499e4280-8f56-11eb-9d8b-60210ea7f809.png)

**Comment by khushishikhu** [comment]
@vismitap add the button named as "signup" on the navbar linked with this LoginPage I have mentioned in the issue description

**Comment by akshitakanojia** [comment]
Hi @khushishikhu  can I work on this issue?

**Comment by vismitap** [comment]
> Hi @khushishikhu can I work on this issue?

This issue was for the old site which didn't have the navbar. It will be closed by @khushishikhu.
