### ISSUE TITLE
Hover effects on "Read More" and Cards in Tips Section

### ISSUE THREAD

**Issue by Saatvik21** [Feminine-Divine/periodo#138]
## Is your feature request related to a problem? Please describe.

Currently there are no hover effects on the cards and the page looks still (TIPS SECTION)

## Describe the solution you'd like

I would like to add hover effects on the "read more" button as well as the cards.

## Additional context

Kindly assign me this issue under GSSoC'21.

**Comment by soulsurya** [comment]
hello,
i'm Suryakant , i can make the cards more attractive by using hover effects , i have previous experience in this and it will be great if you assign me this issue under GSSoC'21

**Comment by khushishikhu** [comment]
@Saatvik21 Thank you so much for opening this issue. Assigning this to you. @soulsurya you can look for any other issue of the project as he has already asked for assigning
