### ISSUE TITLE
Decide the content for "Tips"

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#14]
## Description
Add the section about Health remedies and write in it what could be the possible things which should be followed. 
Also a section for Medicine to be taken during the period for pain. 

## To get merged
Discussed with at least one mentor

**Comment by nishihere19** [comment]
I would like to work on this under gssoc'21.

**Comment by khushishikhu** [comment]
@nishihere19 I can assign you to only one issue at a time. When you are done with your previous issue do comment again. I will happily assign you ☺️

**Comment by nishihere19** [comment]
Sure.

**Comment by Nidhikamewar15** [comment]
I would like to work on this under GSSoC'21.

**Comment by Riya764** [comment]
I would like to work on this under gssoc'21.

**Comment by Riya764** [comment]
I would like to work on this under GSSoC'21.

**Comment by khushishikhu** [comment]
@Nidhikamewar15  Assigning this to you are the next in the line who have asked. Make sure to give us the update within 3 days as then I have to assign someone else who is in the queue. Happy coding

**Comment by Nidhikamewar15** [comment]
Thank you for assigning the issue to me. Can you please clarify what exactly I am supposed to do? 
Like I only have to provide the content regarding the same or I have to add a separate HTML page to the website having the tips?

**Comment by khushishikhu** [comment]
@Nidhikamewar15 currently just give us the content which needs to be written on the website. You don't need to create any HTML page or folder like that. Because this content will be added in the Tips Page of the App when that page will be ready.

**Comment by Nidhikamewar15** [comment]
How I am supposed to submit the content, it's ready?

**Comment by Nidhikamewar15** [comment]
How can I submit the content file?

**Comment by khushishikhu** [comment]
@Nidhikamewar15 Make a PR and write in it what all the content needs to be added.

**Comment by khushishikhu** [comment]
@Nidhikamewar15 please refer to the PR #13 You have to decide the content for those cards .
