### ISSUE TITLE
Adding a graphs for data visualization

### ISSUE THREAD

**Issue by loneWarrior581** [Feminine-Divine/periodo#140]
## Is your feature request related to a problem? Please describe.
The current version of application dose not contain any feature for visualizing the data based on based on his **daily survey** taken on the application at `/flow`. A line graph would be created on his daily survey that she marks so that she can put a track on her past record and would be easy for her prescription and also would help her to predict her future events if any.

## Additional context
A further more step would be taken by showing her past graph(Line) so that he can compare between the past record and take perception of the doctor is the situation has not improved much since her last period.

**Comment by khushishikhu** [comment]
@loneWarrior581 Thank you so much for opening this issue. Would you like to be assigned on this issue?

**Comment by loneWarrior581** [comment]
Sure I would love to work upon this issue .😊

**Comment by subhangi2731** [comment]
@khushishikhu can i work on this please
