### ISSUE TITLE
Logo on top left corner should redirect to home page.

### ISSUE THREAD

**Issue by keshavga1209** [Feminine-Divine/periodo#145]
The logo on the top left corner on the navbar of the website should redirect user to the homepage. Right now it does nothing.

**Screenshots**

![image](https://user-images.githubusercontent.com/59997067/112680863-eb109000-8e93-11eb-8380-5e7481893136.png)

Please assign this issue to me.

**Comment by khushishikhu** [comment]
@keshavga1209 assigning this to you. Thank you for opening this issue

**Comment by keshavga1209** [comment]
hey,just a simple query. Never used yarn before. So should I use "yarn install --global" as mentioned in readme or just "yarn install" can do the job. I mean do i really need to install yarn globally just for this project?

**Comment by khushishikhu** [comment]
@keshavga1209  As it is written in the Readme if you don't have yarn installed in your computer. Then you have to use `yarn install --global`
