### ISSUE TITLE
Opaque background.

### ISSUE THREAD

**Issue by padmajabhol** [Feminine-Divine/periodo#148]
**Describe the bug**
Texts on many pages is less visible because of the background.

**To Reproduce**
1. Go to 'landing page'
2. Click on 'gynachelp/about us'

**Expected behavior**
The background image should be opaque and the text must be more visible.

**Screenshots**

![Screenshot (62)](https://user-images.githubusercontent.com/75530516/112734097-b53ddb00-8f69-11eb-9da1-e69f9fd0173b.png)

**Desktop (please complete the following information):**
 - windows:10 [e.g. iOS]
 - chrome[e.g. chrome, safari]

**Smartphone (please complete the following information):**
 - redmi note 8 pro [e.g. iPhone6]
 - chrome [e.g. stock browser, safari]

**Additional context**

**Comment by AakankshaKamal** [comment]
I would like to work on this issue as a gssoc 21 participant.

**Comment by khushishikhu** [comment]
@AakankshaKamal assigning this to you. happy coding!!

**Comment by AakankshaKamal** [comment]
![Screenshot 2021-04-10 115251](https://user-images.githubusercontent.com/58944717/114260570-5fe6dc80-99f3-11eb-906b-e868ae4e8b89.png)
I was thinking to modify the background of the page into something like this so that now it becomes more readable .Please do give your views so that I can modify accordingly.

**Comment by khushishikhu** [comment]
@AakankshaKamal on this particular page only? Because it should not change the background of other pages of have done the changes in home.css file

**Comment by AakankshaKamal** [comment]
The change is only for this particular page only not the others.I haven't changed the global css

**Comment by khushishikhu** [comment]
@AakankshaKamal Then it's fine but I can see in the screenshot that it is not covering the whole form as it is shown in the issue description and

**Comment by AakankshaKamal** [comment]
Yes I updated the project  and in the recent one the gynae form pattern was changed to this way so I made changes in the background to that only

**Comment by khushishikhu** [comment]
@AakankshaKamal okay got it. You can move forward to make a PR. can you add the gradient effect with some light colours in the background? It will look more good

**Comment by AakankshaKamal** [comment]
@khushishikhu  Ok I'll implement it.

**Comment by AakankshaKamal** [comment]
![Screenshot 2021-04-13 184156](https://user-images.githubusercontent.com/58944717/114558172-09460080-9c88-11eb-876e-a43b2e8339a1.png)
![Screenshot 2021-04-13 184224](https://user-images.githubusercontent.com/58944717/114558177-0b0fc400-9c88-11eb-89b7-7b5f3e8d698f.png)
Please do have a look.

**Comment by khushishikhu** [comment]
@AakankshaKamal I really liked this one.

**Comment by AakankshaKamal** [comment]
Thank You @khushishikhu .Kindly look into my PR.Thanks.
