### ISSUE TITLE
Notes not visible clearly.

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#149]
**Describe the bug**
The notes we take are not visible properly as the background not transparent.

**Expected behavior**
The notes should be visible clearly and the background should be transparent.

**Screenshots**
![2021-03-28 (3)](https://user-images.githubusercontent.com/65683151/112734805-0e0f7280-8f6e-11eb-91c7-9a8a79ea8155.png)

**Desktop (please complete the following information):**
 - OS: Windows [e.g. iOS]
 - Browser chrome
 - Version 

**Additional context**

**Comment by akshay1027** [comment]
Just now noticed the same issue has been already raised. Sorry!

**Comment by khushishikhu** [comment]
@akshay1027 where can you please mention that issue here. I haven't find any

**Comment by akshay1027** [comment]
No It's not mentioned specifically, generall it's mentioned. I would be happy to work on this issue @khushishikhu

**Comment by khushishikhu** [comment]
@akshay1027 cool. Assigning this to you. Happy Coding!!

**Comment by akshay1027** [comment]
I have made the changes @khushishikhu , this design is cleaner now. You can suggest any other background colour as well!

![2021-04-03 (1)](https://user-images.githubusercontent.com/65683151/113452388-7ef8d380-9421-11eb-8718-3d6e16a6d503.png)
