### ISSUE TITLE
Hover effect in About Us section.

### ISSUE THREAD

**Issue by padmajabhol** [Feminine-Divine/periodo#153]
## Is your feature request related to a problem? Please describe.
There isn't any hover effect in the about us section cards

## Describe the solution you'd like
I want to add hover effects in that particular section.

**Comment by Vaishnavi798** [comment]
Can I work on this issue as a part of GSSoC'21 ?

**Comment by khushishikhu** [comment]
@Vaishnavi798 yes you can. assigning this to you

**Comment by Muskan-creator** [comment]
Can i work on this issue please ?
