### ISSUE TITLE
Nearby hospitals List

### ISSUE THREAD

**Issue by AakankshaKamal** [Feminine-Divine/periodo#158]
## Is your feature request related to a problem? Please describe.
Sometimes there may be an emergency case where they need to go to a hospital, or for general treatment.

## Describe the solution you'd like
We can include an option to locate the nearby hospital and could also provide directions for it.

**Comment by khushishikhu** [comment]
@AakankshaKamal I liked your idea. Thank you for coming with this issue. wanna work on this issue?

**Comment by AakankshaKamal** [comment]
Yes I would like to work on this issue

**Comment by khushishikhu** [comment]
@AakankshaKamal assigning this to you. Happy coding!!

**Comment by AakankshaKamal** [comment]
Thank You.I'll try my best to implement it. I would like to know where this feature would look better like on the home page or in the gynac help part?

**Comment by khushishikhu** [comment]
@AakankshaKamal on the gynac part

**Comment by subhangi2731** [comment]
@AakankshaKamal are u working on this issue? If not can I work

**Comment by AakankshaKamal** [comment]
@subhangi2731  Yes You can I wont be able to do it right now.

**Comment by subhangi2731** [comment]
thank u @AakankshaKamal can u please assign me this @khushishikhu

**Comment by khushishikhu** [comment]
@subhangi2731 assigned you on this
