### ISSUE TITLE
coding: Add Third-Party Authentication

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#16]
## Description
Add the third party authentication to login in the app through Google account/ Facebook account. And add the sensitive information in environment variables ( .env file)

**Comment by nishihere19** [comment]
I would like to work on this under gssoc'21. I have worked with APIs before as well and I hope I will be able to complete this if assigned.

**Comment by khushishikhu** [comment]
@nishihere19 assigning it to you. Happy coding!!

**Comment by nishihere19** [comment]
Thank you
