### ISSUE TITLE
Bug: Text in 'AboutUs' page disappears in desktop mode

### ISSUE THREAD

**Issue by A-HK** [Feminine-Divine/periodo#162]
**Describe the bug**

In desktop mode, some lines of description in the AboutUs page below 'How We Help' are currently not visible.

What it looks like currently:
![after_fork](https://user-images.githubusercontent.com/73497800/113193705-e70eb480-927d-11eb-8c44-fa57983ddc1e.png)

What it should look like (Expected Behaviour):
![before_fork](https://user-images.githubusercontent.com/73497800/113193447-98f9b100-927d-11eb-8594-4e64eacd8c08.png)

Additionally, in mobile view, only one expected line of text appears:
![after_fork_mobile](https://user-images.githubusercontent.com/73497800/113193820-07d70a00-927e-11eb-9e5f-9d517fc92d5c.png)

**To Reproduce**
1. Go to 'AboutUs' page
4. Notice that two lines of the subheading are missing.

**Expected behavior**

Expected text (below the heading) must be displayed properly in all modes, for all screen sizes.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional Context**
The required text is already included in the aboutstyle.js file, it just needs to be made visible.

**Comment by mis-coder** [comment]
Hi! I would like to give it a try. Please assign it to me.

**Comment by mis-coder** [comment]
![screenshot](https://user-images.githubusercontent.com/51118723/113248019-cd02bf80-92d9-11eb-84dd-7cd218302769.PNG)

I tried to increase the margin-top to check where the problem lies. We just need to adjust their position..

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu yes i am ready to do this i can fix it :)))

**Comment by Aaishpra** [comment]
@mis-coder can you look for other issue actually we had already talked about it with @satavshreya so assigning him here.

**Comment by mis-coder** [comment]
> @mis-coder can you look for other issue actually we had already talked about it with @satavshreya so assigning him here.

No problem! I wanted to solve it and i did😊

**Comment by satavshreya** [comment]
![2021-04-01 (2)](https://user-images.githubusercontent.com/61575173/113282739-fab12e00-9304-11eb-81cc-3aafd0e68be2.png)
![2021-04-01 (5)](https://user-images.githubusercontent.com/61575173/113282743-fbe25b00-9304-11eb-864a-8a594da8514f.png)
Check this out ! Any more changes? Ready for that

**Comment by Aaishpra** [comment]
Looks good submit the PR, i will review it by eod.
