### ISSUE TITLE
UI of card can be improved in notes page

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#166]
**Describe the bug**
UI of the card can be improved in the notes page.

**Comment by akshay1027** [comment]
changes am thinking to make @khushishikhu ,
1) make the title different from content
2) add hover effect
3) improve card design

**Comment by khushishikhu** [comment]
@akshay1027 make all these changes in that PR which is already assigned to you. No need to create a new issue and PR for the same thing. Thank you for showing your interest. Keep contributing
