### ISSUE TITLE
contact us in footer

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#167]
**Describe the bug**
improve footer UI

**Comment by akshay1027** [comment]
Can i get an update on this? @khushishikhu

**Comment by Aaishpra** [comment]
U can add a contact us form instead of improving the ui, cuz we just got a new footer and i plan on keeping it.

**Comment by akshay1027** [comment]
Improvements we can add to Footer are @Aaishpra :
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Comment by akshay1027** [comment]
I would like to work on this! would be happy to see the current footer design as well, please share screenshot @Aaishpra

**Comment by Aaishpra** [comment]
Check the deployed website, there the footer is available

**Comment by Aaishpra** [comment]
> @Aaishpra
> Improvements we can add to Footer are :
> 1)Find us with logo
> 2)Call us with logo
> 3)Mail us with logo
> 4)Website logo
> 5)What this website is about
> 6)Follow us
> -Instagram link with logo
> -LinkedIn link with logo
> -Twitter link with logo
> -etc
> 7)Useful links
> -Home
> -Services
> -About Us
> -Contact Us etc
> 8)Subscribe
> -Email address
> 9)Copyrights
> 10) All the above with responsive UI

About this we don't have a number dedicated to website currently hence no call us, no website currently for organisation,no Instagram, no Twitter,no YouTube for subscribing, we just have a LinkedIn page dedicated to organisation which is also not very active.
Please again checkout the footer and i suggest you can make a contact us form in footer instead of all this.

**Comment by akshay1027** [comment]
Ohh okay then! Sure , I will take up contact us issue! @Aaishpra
