### ISSUE TITLE
Hover Effect to Continue button in Log in Page

### ISSUE THREAD

**Issue by n-coder2k** [Feminine-Divine/periodo#170]
I would like to add hover effect to continue button in login page.
I am gssoc participant , please assign me this issue.

**Comment by khushishikhu** [comment]
@n-coder2k okay assigning this to you

**Comment by n-coder2k** [comment]
@khushishikhu I am not familier with this framework i won't be able to do this.

**Comment by iamRishabh07** [comment]
@khushishikhu I want to work on this issue can you assign me this issue.

**Comment by raks924** [comment]
I am a GSSOC'21 participant. Would love to work on this issue. kindly assign it to me?

**Comment by khushishikhu** [comment]
@iamRishabh07 assigning this to you. Happy Coding!!
