### ISSUE TITLE
Beautification of Gyane help page

### ISSUE THREAD

**Issue by n-coder2k** [Feminine-Divine/periodo#171]
I would like to beautify the gynae help page by changing font color and type and removing extra spaces.
I am gssoc participant please assign me this issue.

**Comment by khushishikhu** [comment]
@n-coder2k assigning this to you. happy coding!!

**Comment by n-coder2k** [comment]
@khushishikhu I am not able to find html file . I am new to opensource please help to find that.

**Comment by khushishikhu** [comment]
@n-coder2k there is no html file in this repository. This project is built by Nextjs framework. You will find about this gyane files in pages folder and in components

**Comment by n-coder2k** [comment]
@khushishikhu I am completely new to Nextjs framework , I wont be able to do this.

**Comment by akshay1027** [comment]
i would like to work on this! @khushishikhu @Aaishpra

**Comment by khushishikhu** [comment]
@akshay1027 assigning this to you. Happy coding!!
