### ISSUE TITLE
In home page, click to chat button design can be changed

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#173]
**Describe the bug**
In the home page, click to chat button design can be changed to make it look more professional.

**Comment by Fpj-11** [comment]
I am interested in front-end development. Kindly assign this issue to me.

**Comment by khushishikhu** [comment]
@Fpj-11  well it's already changed but if you want to improve it more. Then assigning this to you. Happy Coding!!

**Comment by akshay1027** [comment]
i wanted to work on this @khushishikhu , hence created the issue and described the bug :)

**Comment by Aaishpra** [comment]
just a suggestion can we use this for the chat button, I just mean using the chat button not anything else in the design.
https://codepen.io/Victoro08/pen/arYJPO

**Comment by akshay1027** [comment]
Sure I would like to this @Aaishpra

**Comment by akshay1027** [comment]
is anyone doing this? @Aaishpra @khushishikhu

**Comment by khushishikhu** [comment]
@akshay1027 assigning this to you. happy coding!!

**Comment by khushishikhu** [comment]
@akshay1027 Sorry, but someone who was assigned has already made the PR and working on this. You can take any other issue and I have assigned you in one
