### ISSUE TITLE
title card UI in notes page can be improved

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#174]
**Describe the bug**
title card UI in notes page can be improved @khushishikhu

**Comment by khushishikhu** [comment]
@akshay1027 please describe whichever issue you are opening. Bcoz it would be difficult for another person to understand

**Comment by akshay1027** [comment]
sorry! i meant this title card @khushishikhu 

![2021-04-03 (4)_LI](https://user-images.githubusercontent.com/65683151/113482654-44447900-94bd-11eb-9d50-7440ab07d505.jpg)

**Comment by khushishikhu** [comment]
@akshay1027 okay as you are already assigned on a issue. so make it available for other participants too. and if you are done with your issue and want to work I will you on this

**Comment by akshay1027** [comment]
yes that issue is done! would love to work on this!
