### ISSUE TITLE
Links in the readme to open in a new tab 

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#177]
## 📚 Documentation

Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by akshay1027** [comment]
i would like to do this!

**Comment by Aaishpra** [comment]
And what's the purpose opening links in a new tab from readme will serve, please elaborate the issue description more.
Thanks

**Comment by akshay1027** [comment]
I found out now that we can't do this on Github! here is the link to that: mojombo/github-flavored-markdown#28
so I will close this.
