### ISSUE TITLE
Creating a Custom Scrollbar to the website

### ISSUE THREAD

**Issue by DEEPALI-SUK** [Feminine-Divine/periodo#178]
## Is your feature request related to a problem? Please describe.
To make website more attractive and beautiful, I want to add a custom scrollbar. Giving a nice CSS to the scrollbar will enhance the UI of the website.

## Describe the solution you'd like
Giving a nice CSS to the scrollbar will enhance the UI of the website. I would like to work on this issue.

Kindly, assign me this issue as a part of GSSOC21.

**Comment by vanshika2906** [comment]
Hi I am a GSSOC participant. Would like to work on this issue.Please assign it to me.

**Comment by Aaishpra** [comment]
Since @DEEPALI-SUK opened this issue assigning this to her you can look for other issues @vanshika2906
