### ISSUE TITLE
Changing Link In the Tab to a Name

### ISSUE THREAD

**Issue by vanshika2906** [Feminine-Divine/periodo#182]
**Describe the bug**
While going to website it's showing the exact link. Want to change this link to a name like "Periodo App".
Please refer to highlighted part in the image.
![image](https://user-images.githubusercontent.com/65587816/113608694-852cc100-9668-11eb-8fe8-af86b8772092.png)

**Comment by vanshika2906** [comment]
I am GSSoC paricipant and want to work on this issue. Please assign this to me. Thankyou!

**Comment by Aaishpra** [comment]
Go forward
