### ISSUE TITLE
About us Page fixation 

### ISSUE THREAD

**Issue by Castella1313** [Feminine-Divine/periodo#188]
About us component is overlapping with the Navbar

![Screenshot 2021-04-08 at 9 09 02 PM](https://user-images.githubusercontent.com/53293156/114055899-c7dfda80-98ae-11eb-90e3-a5bdb5dae6f0.png)

**Comment by Castella1313** [comment]
@Aaishpra May I work on it?

**Comment by khushishikhu** [comment]
@Castella1313 assigning this to you. happy Coding!!
