### ISSUE TITLE
coding: Add more ratings 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#19]
## Description
Add some more relevant Ratings with this.
![image](https://user-images.githubusercontent.com/65439761/110375348-de103600-8077-11eb-9033-e342fb93b854.png)

**Comment by codebuzzer01** [comment]
Hey! I would like to work on it. @khushishikhu

**Comment by khushishikhu** [comment]
@codebuzzer01 assigning this to you. Happy Coding!!
