### ISSUE TITLE
Problem in AboutUs button

### ISSUE THREAD

**Issue by hritikgupta92** [Feminine-Divine/periodo#191]
**Describe the bug**
On clicking the About us button on NavBar,the component for how we help was coming up 
thus cutting the buttons of NavBar,thus degrading the Quality of the site. 

 
**Screenshots**

![image](https://user-images.githubusercontent.com/58954579/114232880-2d5cc580-999a-11eb-9b2d-453c6bb4c306.png)

**Comment by nishihere19** [comment]
Hi, I would like to work on this under GSSOC'21.

**Comment by nishihere19** [comment]
Oh, this is a duplicate of #188 . Kindly close the issue.

**Comment by hritikgupta92** [comment]
ok,thanks for informing
