### ISSUE TITLE
Beautification of the tips page

### ISSUE THREAD

**Issue by ishani02** [Feminine-Divine/periodo#192]
## Is your feature request related to a problem? Please describe.
There is no hover effect on cards in the tips page.

## Describe the solution you'd like
I would like to add hover effect on cards in the tips page. I believe this will enhance the look of the page. When somebody hovers over a card, it’s size will increase while other cards will remain unaffected. I can also change the color of the text "Read more" of the respective card, on hovering, if you are fine with that.

**Comment by ishani02** [comment]
@khushishikhu I would like to work on this issue under GSSoC'21. Kindly assign this issue to me.

**Comment by khushishikhu** [comment]
@ishani02 Thank you for opening this issue. Go ahead
