### ISSUE TITLE
Enhance Tips card with images

### ISSUE THREAD

**Issue by WaderManasi** [Feminine-Divine/periodo#194]
## Describe the solution you'd like
Tips card can be more attractive if we add images related to the tip (eg: Drink tea - we can add png image/logos describing it below its name)

## Additional context
Would like to work being part of gssoc

**Comment by khushishikhu** [comment]
@WaderManasi Thank you for opening this issue. Assigning this to you 👍

**Comment by WaderManasi** [comment]
Hey @khushishikhu,
 just check once..so that I can create PR

![show](https://user-images.githubusercontent.com/52437677/115105990-c2a22000-9f7f-11eb-9fcf-9ad485a483f5.PNG)
