### ISSUE TITLE
Change in footer and bottom scroll bar.

### ISSUE THREAD

**Issue by shriya030** [Feminine-Divine/periodo#195]
I think that the footer color where it is written Made with ❤ should have the same background color as above and also the footer text images should be center-aligned for it to look more appealing.
The horizontal scroll bar should be hidden as it is not looking good.

Can I work on this as a part of GSSOC'21?
![image](https://user-images.githubusercontent.com/56861600/114310317-150ab900-9b08-11eb-93c9-578d78d9e8c5.png)

**Comment by raks924** [comment]
Hey i am a GSSOC'21 participant. Iloved the project. Can I work on this issue?

**Comment by shriya030** [comment]
> I think that the footer color where it is written Made with ❤ should have the same background color as above and also the footer text images should be center-aligned for it to look more appealing.
> The horizontal scroll bar should be hidden as it is not looking good.
> ![image](https://user-images.githubusercontent.com/56861600/114310317-150ab900-9b08-11eb-93c9-578d78d9e8c5.png)

Please assign me this issue as a part of GSSOC'21
