### ISSUE TITLE
Addition of contributor section in readme (Automatically)

### ISSUE THREAD

**Issue by ankit-kmar** [Feminine-Divine/periodo#197]
## Proposal
I would like to add a feature, this will show the contributors in readme section at the end. This will also update contributor list in read me automatically !! 

## Additional context

Kindly assign me this with a gssoc21 label and level tag

**Comment by Aaishpra** [comment]
Sorry @ankit-kmar we are not in need of this feature for our project currently, as this will make the readme very populated which I don't want

**Comment by ankit-kmar** [comment]
okay ma'am!! no issue. But actually I was thinking that instead of the last part where it's mentioned that this repo is a part of GSSoC, if there would be the contributor section, it would look great and more better (personal opinion). But if you don't want it, then you can close the issue :)

**Comment by khushishikhu** [comment]
@ankit-kmar we respect your opinion but currently, we don't want it. Please feel free to open some other kind of issue for improvement of this project.
