### ISSUE TITLE
Improve UI in "/flow" page

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#199]
## Is your feature request related to a problem? Please describe.
The cards can be improved in the "/flow" page!

Additional Context:
this is the page am referring to: 

![2021-04-13 (5)](https://user-images.githubusercontent.com/65683151/114473963-df062b80-9c12-11eb-9af3-02affbb0298a.png)

**Comment by akshay1027** [comment]
I would like to work on this  @khushishikhu @Aaishpra

**Comment by khushishikhu** [comment]
@akshay1027 go ahead. Assigning this to you
