### ISSUE TITLE
docs: Add a PR template

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#2]
## Description
Add the PR template for opening any Pull Request

## Status
Discuss with the mentor.

**Comment by 96RadhikaJadhav** [comment]
@khushishikhu  Can I work on it?

**Comment by khushishikhu** [comment]
@96RadhikaJadhav sure. Assigning this to you☺️

**Comment by khushishikhu** [comment]
@96RadhikaJadhav sure. Assigning this to you☺️

**Comment by khushishikhu** [comment]
@96RadhikaJadhav now you can work on this issue😉

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav now you can work on this issue😉

@khushishikhu  I have created a PR #15 for this. Could you please check and let me know if any other changes required.
