### ISSUE TITLE
feat: Change rating icons

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#20]
## Description
Change the icons of the ratings
![image](https://user-images.githubusercontent.com/65439761/110375597-30515700-8078-11eb-8010-b7e719682f10.png)

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021
Thank you.

**Comment by cicada3006** [comment]
Hey! I would like to work on this project(GSSoC 21)

**Comment by khushishikhu** [comment]
@shairanshrawat assigning this to you. Happy Coding

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by shairanshrawat** [comment]
> @shairanshrawat assigning this to you. Happy Coding

thank you for assigning me 
@khushishikhu I have some doubts regarding the work where can I communicate to you here or on discord

**Comment by shairanshrawat** [comment]
hey @khushishikhu 
the Github link in the readme file is still private. Lemme know how can I communicate to you so that I can start working on the issues

**Comment by khushishikhu** [comment]
@shairanshrawat you can ask here for any queries. We will guide you in every possible way.

**Comment by shairanshrawat** [comment]
@khushishikhu I wanna ask that you want the design to be made in figma or in css (I have to code and change it )

**Comment by khushishikhu** [comment]
@shairanshrawat if you are comfortable then make a design on figma or you can use something else which ever you like.

**Comment by shairanshrawat** [comment]
Hey @khushishikhu  I made the page. Please review and suggest any changes that need to be made [Figma link](https://www.figma.com/file/gCgZ9vu1gnPoajCps9w9Gz/Periodo?node-id=0%3A1)

**Comment by khushishikhu** [comment]
@shairanshrawat  we really liked your design for the ratings😍😍.  Just add all those ratings which are currently displayed on the flow page

**Comment by shairanshrawat** [comment]
> @shairanshrawat we really liked your design for the ratings😍😍. Just add all those ratings which are currently displayed on the flow page

hey @khushishikhu can you please elaborate I didn't get it

**Comment by khushishikhu** [comment]
![Capture](https://user-images.githubusercontent.com/65439761/111177853-a271f080-85d0-11eb-9078-01528f97a811.PNG)
@shairanshrawat you need to change the icons of all these ratings. Just add all these ratings in your figma design. I hope you get it now.

**Comment by shairanshrawat** [comment]
> ![Capture](https://user-images.githubusercontent.com/65439761/111177853-a271f080-85d0-11eb-9078-01528f97a811.PNG)
> @shairanshrawat you need to change the icons of all these ratings. Just add all these ratings in your figma design. I hope you get it now.

@khushishikhu so I have to add all these categories that are there in this picture also with the icons like I have put in my Figma file right?
one more thing you want the same background as in this picture or something else?

**Comment by khushishikhu** [comment]
@shairanshrawat yes you it right, No the background should be like your figma file that you have designed as we really loved that😍.

**Comment by shairanshrawat** [comment]
> @shairanshrawat yes you it right, No the background should be like your figma file that you have designed as we really loved that😍.

I'm glad you like it, okay I get all of it, will get back to you asap after finishing

**Comment by shairanshrawat** [comment]
@khushishikhu I have edited the design have a look at [FIGMA LINK](https://www.figma.com/file/gCgZ9vu1gnPoajCps9w9Gz/Periodo?node-id=0%3A1). Lemme know if any modification is required

**Comment by shairanshrawat** [comment]
hey, @khushishikhu did you checked the design?

**Comment by shairanshrawat** [comment]
if they are okay can I make a PR for the same

**Comment by khushishikhu** [comment]
@shairanshrawat yes yes, please they are wonderful. I would liked it a lot of you make it into action. Sorry I just got completely forgotten about this because of my exams. Please go ahead 😉

**Comment by shairanshrawat** [comment]
hey @khushishikhu I have made the PR 4 days ago I hope it's not creating any issues as it's not merge yet
