### ISSUE TITLE
Home Page Navbar Alignment 

### ISSUE THREAD

**Issue by anhushree** [Feminine-Divine/periodo#200]
## Is your feature request related to a problem? Please describe.
The content in the  Header section-Navbar is centralized. which is not visually pleasing. Hence the alignment of the elements can be adjusted

## Describe the solution you'd like
The Home button can be placed on the leftmost side, while the rest can be placed on the rightmost side following this order-About Us, Notes, Tips, GynacHelp, Quiz, Calendar, Login.
In addition to this, adding Icons might improve the User Experience. Hence I would like to add related Icons as well.

Image:
![image](https://user-images.githubusercontent.com/56672958/114508507-0f20ef00-9c52-11eb-91a8-772c33b53f22.png)

**Comment by anhushree** [comment]
@akshitakanojia Could you please assign me this task? I would like to work on improving the UX of this layout in the navbar

**Comment by khushishikhu** [comment]
@anhushree assigning this to you

**Comment by anhushree** [comment]
Thank You so much will start working on it.

**Comment by anhushree** [comment]
@khushishikhu can u please assign the labels and level? I'm a GSSoC'21 participant. Apparently, those with labels and levels are only counted. Mine has not been done during the PR merge, kindly check and help me out.
