### ISSUE TITLE
Enhance and modify "Do you want to share your period experience?" prompt

### ISSUE THREAD

**Issue by satavshreya** [Feminine-Divine/periodo#202]
I think it can be modified more attractively because I think the current one is fine but not creating a good view Tell me how do you feel  else I am ready to modify :) @Aaishpra @khushishikhu 
![image](https://user-images.githubusercontent.com/61575173/114662323-1dd0da00-9d16-11eb-8c54-31e49d705688.png)

**Comment by Aaishpra** [comment]
Do share the design after you are done @satavshreya assigning you here

**Comment by satavshreya** [comment]
BEFORE hovering it looks like:
![image](https://user-images.githubusercontent.com/61575173/114705445-5f2cae00-9d45-11eb-8b93-d81dd658f85b.png)

AFTER hovering it looks like:
![image](https://user-images.githubusercontent.com/61575173/114705462-63f16200-9d45-11eb-9fbe-5c50da09071e.png)

@Aaishpra @khushishikhu let me know if any changes :)

**Comment by Aaishpra** [comment]
Make the after and before opposite, means the button should be lighter before hovering and vice versa। Change the button colour after hovering to the earlier used colour. Current colour looks a bit too dark for the website

**Comment by satavshreya** [comment]
okay So check this out:
![image](https://user-images.githubusercontent.com/61575173/114711673-de71b000-9d4c-11eb-9a72-2aa1549e244f.png)
![image](https://user-images.githubusercontent.com/61575173/114711715-e9c4db80-9d4c-11eb-8103-346493720b86.png)

**Comment by Aaishpra** [comment]
Yupp, go with the PR now
