### ISSUE TITLE
coding: create a Quiz 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#21]
## Description
Create a Quiz by making any new page with the name "Analysis" of five questions on what do Girls feel during Periods. The Questions can have like How is pain or how is blood flow , like that.

**Comment by anshika208** [comment]
Hey! I will like to work on this @khushishikhu !

**Comment by khushishikhu** [comment]
@anshika208 assigning this to you. Happy Coding!!

**Comment by Esha-Sherring** [comment]
I would also like to work on this issue

**Comment by priyaverma20** [comment]
I would to work on this

**Comment by prerna2712** [comment]
I would like to work on this issue under GSSOC '21.

**Comment by anshika208** [comment]
Hey! I m still working on the issue just need some more time....

**Comment by khushishikhu** [comment]
@anshika208 okay, Take your time and send us PR as soon as possible 😉

**Comment by anshika208** [comment]
hey! i have made the page and ready to push the changes but i m getting merge conflict
