### ISSUE TITLE
Responsive website

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#211]
**Describe the bug**

The home page is not responsive for mobile view 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/61223163/115256258-b0c1a800-a14c-11eb-9f77-d6d525001f52.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

I want to work on this issue to make the website mobile friendly

**Comment by Aaishpra** [comment]
Thanks for the issue @gnikita432 assigning you here.
Happy coding

**Comment by gnikita432** [comment]
Thanks for assigning the issue.
