### ISSUE TITLE
Updating the Contributing guidelines

### ISSUE THREAD

**Issue by K-Kumar-01** [Feminine-Divine/periodo#215]
## 📚 Documentation

The contributing guidelines can be updated to improve the commit message qualities. These will ensure better readability and understandability of the changes made in the commit.

### Would you like to work on this?
Yes

**Comment by khushishikhu** [comment]
@K-Kumar-01 Thank you for opening this issue. Assigning you to this

**Comment by KajalSinghBAGHEL** [comment]
I am girlscript participate may i work on this issue

**Comment by K-Kumar-01** [comment]
@KajalSinghBAGHEL 
I have completed the work actuallly and am about to make a PR.
