### ISSUE TITLE
Design a logo for Feminine-Divine

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/periodo#219]
## Is your feature request related to a problem? Please describe.

Design a logo for feminine divine
## Describe the solution you'd like

Two logos required on for smaller screen one for full size
## Additional context

Please show your designs in the comments and add them to assets folder after they get approved

**Comment by satavshreya** [comment]
@Aaishpra can i work on this please???

**Comment by Aaishpra** [comment]
Ya sure @satavshreya assigned you here

**Comment by satavshreya** [comment]
![image](https://user-images.githubusercontent.com/61575173/115850576-a270d600-a443-11eb-8275-5bc39a35efc9.png)
i came up with this

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu once just let me know what all should i put in logo so that i can some up with 4-5 designs :)

**Comment by Aaishpra** [comment]
@satavshreya this is a logo for periodo, i need one for the organization,
basically, I am looking for something which signifies the power of femininity may be an illustration of women something like that for a smaller screen, and the illustration and organization name for a bigger screen logo.

**Comment by satavshreya** [comment]
@Aaishpra  yes i got your point! I will make one and paste here :)

**Comment by satavshreya** [comment]
![Feminine Divine](https://user-images.githubusercontent.com/61575173/115949212-19b07380-a4f1-11eb-9dc2-3116ec4810d5.png)

**Comment by satavshreya** [comment]
![Feminine Divine (1)](https://user-images.githubusercontent.com/61575173/115949473-07373980-a4f3-11eb-8c53-a8f4fdac7c00.png)

**Comment by Aaishpra** [comment]
2nd one feels better to me, let's ask @khushishikhu

**Comment by khushishikhu** [comment]
> 2nd one feels better to me, let's ask @khushishikhu 

I feel the same. Please approve this @Aaishpra

**Comment by Aaishpra** [comment]
@satavshreya please send a PR for the second logo
