### ISSUE TITLE
Coding: Prescriptions

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#22]
## Description
According to the marks in quiz. Give the user the links to go for the page where all the remedies and Prescription are listed for the time Being as it will be added in the Tips Page

**Comment by mdPial** [comment]
I would like to work on that issue.

**Comment by micksharma** [comment]
I want to work on this issue as a GSSOC participant 2021.

**Comment by Riya764** [comment]
Can I work on this issue as a part of GSSOC 2021?

**Comment by khushishikhu** [comment]
@micksharma assigning this to you. Happy coding!!

**Comment by khushishikhu** [comment]
@Riya764 as there is already someone before you who has asked so I have assigned the to him. You can look for some other issues also in the project. I hope you got my point. For us every Participant is valuable.

**Comment by mdPial** [comment]
@khushishikhu Do I have to wait for my PR merged to work on another issue? My PR changes already approved.

**Comment by Aaishpra** [comment]
@micksharma updates??

**Comment by vismitap** [comment]
May I work on this issue as a part of GSSoC'21?

**Comment by A-HK** [comment]
Hey @khushishikhu @Aaishpra , if nobody's working on this currently, may I try contributing to this issue?

**Comment by khushishikhu** [comment]
@A-HK yes sure, please go ahead

**Comment by A-HK** [comment]
Hey @Aaishpra @khushishikhu , would appreciate it if  you give me a few pointers on how to go about this issue when you have a few minutes to spare.

- For instance, do you want me to create a separate dedicated 'Prescriptions' page which the quiz would lead to, or do you want it to lead to a specific card on the 'Tips' page?

- Also would like some clarity on whether the results should be determined based on a numeric score (like 4/5) in the quiz, or give the suggestion catered to each question's response ( E.g. If extreme pain -> one suggestion ; if mood swings -> another suggestion, etc. )

Thanks for your time !

**Comment by khushishikhu** [comment]
@A-HK I want to the thing should go like , the user will get the suggestion show up for what do to next in that page only or you can also make a pop up for what to do next according to her score in the quiz , the second you have written is the exact thing what I need here. Thank you for showing your interest , I hope this cleared your confusion if still any confusion left in your mind feel free to pings us, we will help you✌️

**Comment by Aaishpra** [comment]
Really which lines, this wasn't intentional can you share the screenshot ar anything else to help us look into it.

**Comment by A-HK** [comment]
This was before I updated my fork
![before_fork](https://user-images.githubusercontent.com/73497800/113089147-a757b680-9204-11eb-8a18-a8d9f4c92c32.png)

And this is how it looks right now ( even in the deployed vercel app )
![after_fork](https://user-images.githubusercontent.com/73497800/113089154-acb50100-9204-11eb-96d6-e6f1f485b5d1.png)

Strangely, when I enter mobile mode, one of the lines appears, and I can't figure out why!
![after_fork_mobile](https://user-images.githubusercontent.com/73497800/113089157-b0e11e80-9204-11eb-8d4e-0084dd97933c.png)

**Comment by khushishikhu** [comment]
@A-HK Thank you for making us aware of this issue. Can you please make a new issue regarding this bug and if you yourself wants to work on this issue by making a separate PR, tell us we will assign you

**Comment by Aaishpra** [comment]
Hey @A-HK no problem take your time we can understand your situation because we also just gave our end sems and it was exhausting for us to manage both project and exams side by side, so you can definitely focus on your exams currently. 
Good luck for your exams. Hope they go well.🙌🏻

**Comment by Aaishpra** [comment]
Btw love your work you can resume it after exams

**Comment by A-HK** [comment]
Hey @khushishikhu @Aaishpra , thanks a ton for your patience!
I'm nearly done!
Please feel free to suggest any changes you would like.

![quiz_1](https://user-images.githubusercontent.com/73497800/115120572-cc517500-9fcb-11eb-9841-972cc875e3c5.png)
![quiz_2](https://user-images.githubusercontent.com/73497800/115120575-cf4c6580-9fcb-11eb-90d1-7ae57a5f2b11.png)
![quiz_3](https://user-images.githubusercontent.com/73497800/115120580-d2dfec80-9fcb-11eb-9366-8f3dcb5be7c1.png)

**Comment by khushishikhu** [comment]
@A-HK please go forward to make a PR
