### ISSUE TITLE
Setting up ESLint in the project

### ISSUE THREAD

**Issue by K-Kumar-01** [Feminine-Divine/periodo#223]
## Is your feature request related to a problem? Please describe.

As the project grows bigger, it is important that the code is linted properly to ensure the consistency and quality of the code
To achieve this, we should set up ESLint in the project.

**Comment by subhangi2731** [comment]
please assign me this

**Comment by Aaishpra** [comment]
Assigned

**Comment by Aaishpra** [comment]
Related to #220

**Comment by subhangi2731** [comment]
@Aaishpra I am working on this. I will make a pr by today surely

**Comment by K-Kumar-01** [comment]
@subhangi2731 
A PR regarding this has already been made. So it would be better if you choose any other issue to solve.

**Comment by Aaishpra** [comment]
Hi @subhangi2731 Sorry for the inconvenience the issue got solved by a different PR already, but don't worry i will open a new issue by tomorrow and assign that to you.🤗

**Comment by subhangi2731** [comment]
I was working on this since many days. Still thank you @Aaishpra for understanding. sure please assign me on a different issue tomorrow
