### ISSUE TITLE
New footer design, feature request!

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#229]
## Is your feature request related to a problem? Please describe.
The footer can be improved.

take a look at this: 
  
When hovered over icon!

![2021-04-19 (1)](https://user-images.githubusercontent.com/65683151/115919023-e7255d00-a495-11eb-98f9-34c6c73c40da.png)

  
  

![2021-04-19](https://user-images.githubusercontent.com/65683151/115919030-e8ef2080-a495-11eb-8bfb-dedf5e146f01.png)

**Comment by akshay1027** [comment]
I made this recently! Would love to do the same for periodo website as well! Let me @Aaishpra @khushishikhu. Thank you

**Comment by khushishikhu** [comment]
@akshay1027 we would love it if you can implement this feature to Periodo as well😍
