### ISSUE TITLE
Bug in navbar

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#231]
**Describe the bug**
The distance between Gyanchelp and the about us link is pretty big compared with other links in the navbar. I don't know if we can resolve this, but would like to work on this! @khushishikhu @Aaishpra 

![2021-04-24 (2)](https://user-images.githubusercontent.com/65683151/115957421-fc46ce00-a51f-11eb-9fb2-e3537bd33e72.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by khushishikhu** [comment]
@akshay1027 I don't think it is a bug. The page fine

**Comment by akshay1027** [comment]
Cool, if it's fine then no problem or else I would be happy to change it
