### ISSUE TITLE
bug: Next button on calendar page

### ISSUE THREAD

**Issue by SandeepKrSuman** [Feminine-Divine/periodo#236]
**Describe the bug**  
  
Currently the 'Next' button is displayed beside the calendar even there is no date selected. The problem here is on clicking the next button it takes to the rating page even there is no dates selected. 

![periodoissue](https://user-images.githubusercontent.com/54541515/116060504-92553280-a69f-11eb-9ae5-41fd8a714eaa.gif)

**Propose a Solution**
- The next button should appear on the calendar only when dates are selected just as the reset button appears. 
- The next button should appear along with the reset button. This will give user both the options at once whether they want to reset by clicking reset or want to go ahead with the selected dates by clicking next.

**Comment by khushishikhu** [comment]
@SandeepKrSuman  Thank you for opening this issue. Assigning this to you

**Comment by SandeepKrSuman** [comment]
Thanks @khushishikhu I'm working on this.
