### ISSUE TITLE
Add footer to all the pages 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#237]
## Is your feature request related to a problem? Please describe.

Add the footer similar to the homepage(just don't add the contact form in that footer) to all other pages of the website too

**Comment by akshitakanojia** [comment]
@khushishikhu can I work on this issue?

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by khushishikhu** [comment]
@akshitakanojia assigning this to you
