### ISSUE TITLE
Design: Create a Logo 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#24]
## Description
Create the Logo for the Project that needs to be put in the corner of the navbar

**Comment by subhangi2731** [comment]
can you assign this to me?

**Comment by ritesh1731** [comment]
I would like to contribute to this under GSSOC21. Can you assign me?

**Comment by khushishikhu** [comment]
@ritesh1731 Assigning this to you. Happy Coding!!

**Comment by khushishikhu** [comment]
@ritesh1731 Thank you so much. I Liked all of them. But we can put only one ,so Last one is the most suitable.

**Comment by khushishikhu** [comment]
Let's take a review from @Aaishpra too.

**Comment by khushishikhu** [comment]
@ritesh1731  Here is a suggestion for the logo. If you can add the girl (which is in the third logo) in the 2nd design of logo. It would look better I think. Please let me know if you can do that and show me after you are done with the changes .

**Comment by ritesh1731** [comment]
Yes, I can try it.

**Comment by ritesh1731** [comment]
Here are some of the changes in logo. Please review it
![Screenshot (335)](https://user-images.githubusercontent.com/59248269/110765447-3020a980-827a-11eb-9ed3-c436f4137df9.png)
![Screenshot (336)](https://user-images.githubusercontent.com/59248269/110765451-31ea6d00-827a-11eb-8f75-078bea6a87fa.png)

...

**Comment by Aaishpra** [comment]
Loved the 2nd one, go with it
