### ISSUE TITLE
Improve UI of contact us form!

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#240]
## Is your feature request related to a problem? Please describe.
The colour of the contact us form can be changed to something that matches the existing UI. The present colour matches the old footer but now it seems irrelevant! Also would like to add box shadows etc to make clean UI

**Comment by akshay1027** [comment]
would love to work on this @khushishikhu @Aaishpra

**Comment by K-Kumar-01** [comment]
@akshay1027 
In my opinion, we should first complete #185 and then move on to this one.

**Comment by akshay1027** [comment]
Sure @k-kumar-01, the backend works for me, I have tested and provided the screenshots, you have tested it as well? Any problems we are facing? if yes let me know, so that we can finish it and move on to next issues 🙌🏻

**Comment by K-Kumar-01** [comment]
@akshay1027 
Sorry I wasn't able to test. Been a bit busy these days. I Will review it ASAP and let you know

**Comment by akshay1027** [comment]
I have sent the video from where I learnt it, check it out to know the working of code
