### ISSUE TITLE
make the webpage responsive

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#242]
**Describe the bug**

Fix the unusual display of homepage for this dimension

**To Reproduce**
1. Go to 'Homepage'
2. Click on the 'toggle button'
3. See error

**Expected behavior**

**Screenshots**

![WhatsApp Image 2021-04-27 at 16 36 21](https://user-images.githubusercontent.com/65439761/116232095-4c6b9d80-a777-11eb-97ff-4399272e1a82.jpeg)

**Smartphone (please complete the following information):**

**Comment by akshitakanojia** [comment]
@khushishikhu I would like to work on this issue
