### ISSUE TITLE
fix the bug

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#243]
**Describe the bug**

Make the page responsive

**To Reproduce**
1. Go to 'Quiz'
2. See error

**Expected behavior**

**Screenshots**

![WhatsApp Image 2021-04-27 at 16 36 18](https://user-images.githubusercontent.com/65439761/116232463-ca2fa900-a777-11eb-93dc-0829c252c126.jpeg)

**Smartphone (please complete the following information):**

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by khushishikhu** [comment]
@AshuKV assigned
