### ISSUE TITLE
The content of navbar is in upper side of icon

### ISSUE THREAD

**Issue by RuchiGitHu** [Feminine-Divine/periodo#246]
## Is your feature request related to a problem? Please describe.
The content of navbar is flying above to icon of that. Also the buttons of navbar looks so congested. 

## Describe the solution you'd like
I want to put some space there and aligned in structural manner.

![image](https://user-images.githubusercontent.com/71754179/116591560-9487ed00-a93c-11eb-84d1-fa3bed9dc501.png)

**Comment by khushishikhu** [comment]
@RuchiGitHu  assigned
