### ISSUE TITLE
Talk with us form background

### ISSUE THREAD

**Issue by RuchiGitHu** [Feminine-Divine/periodo#247]
## Is your feature request related to a problem? Please describe.
Like landing page, the background and images gives good user experience. Like that I want to put some creativity in Talk with us form. So, that it can look similar like landing page of website...

## Describe the solution you'd like
I can put some creativity that will surely match the theme of website. And look pretty good and creative. 

## Additional context
![image](https://user-images.githubusercontent.com/71754179/116592469-aa49e200-a93d-11eb-9d8c-9bb356ff8bf2.png)

**Comment by K-Kumar-01** [comment]
@RuchiGitHu Can you share some samples regarding the same?

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu Can you share some samples regarding the same?

![IMG_20210501_131718](https://user-images.githubusercontent.com/71754179/116775247-a4f4b080-aa7f-11eb-9947-e3d115ed9a5a.jpg)
It's an contact us form in a image, but a rough idea about background for a form.

**Comment by RuchiGitHu** [comment]
> > @RuchiGitHu Can you share some samples regarding the same?
> 
> ![IMG_20210501_131718](https://user-images.githubusercontent.com/71754179/116775247-a4f4b080-aa7f-11eb-9947-e3d115ed9a5a.jpg)
> It's an contact us form in a image, but a rough idea about background for a form. @K-Kumar-01 please assign this issue to me...

Please look into here @K-Kumar-01

**Comment by khushishikhu** [comment]
@RuchiGitHu sorry but we don't like to have any change in the background. Thank you for showing your consult, keep opening new issues for the improvement of the website
