### ISSUE TITLE
Common Layout

### ISSUE THREAD

**Issue by K-Kumar-01** [Feminine-Divine/periodo#249]
## Is your feature request related to a problem? Please describe.

Navbar and footer are currently used in many pages. So instead of importing them in all pages separately. there should be a layout in which these are imported and the layout page is imported in individual pages then.

## Describe the solution you'd like

Create a custom Layout component that imports header and footer and renders children accordingly.

**Comment by vanshika2906** [comment]
Kindly assign this to me! Thankyou!
