### ISSUE TITLE
Problem in Gynac page

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#254]
**Describe the bug**  

 problem in mobile UI in Gynac page

screenshots:  

![2021-04-30 (9)](https://user-images.githubusercontent.com/65683151/116736814-0419dd00-aa0e-11eb-83f6-5bb4ebc4b172.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akshay1027** [comment]
I would like to work on this @K-Kumar-01 @khushishikhu @Aaishpra

**Comment by raks924** [comment]
i would like to work on this issue.kindly assign it to me.

**Comment by subhangi2731** [comment]
@khushishikhu please assign me this issue

**Comment by khushishikhu** [comment]
@subhangi2731 assigned you
