### ISSUE TITLE
Bug in calander page

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#258]
**Describe the bug**

In mobile view the reset and next button is not responsive(they are too big and taking a lot of space).
Also the initials of day (su,mo...) have very light color so it does not have proper visibility.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/61223163/116809349-3422c680-ab5b-11eb-8665-bd36601987e7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I would like to change the color of the days and make the buttons and text responsive.

**Comment by Aaishpra** [comment]
@gnikita432 go for it.

**Comment by raks924** [comment]
can i work on this issue?
