### ISSUE TITLE
Design: Modify the Calender

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#26]
## Description
Design the Calendar of the Calendar page in the website.

**Comment by Esha-Sherring** [comment]
I would like to work on this issue as a GSSoC'21 participant

**Comment by Riya764** [comment]
I would like to work on this issue as a GSSoC'21 participant

**Comment by KaranKaira** [comment]
I would like to work on this as a GSSoC'21 participant.

**Comment by Bhawna147** [comment]
Please assign this to me

**Comment by satavshreya** [comment]
@khushishikhu  @Aaishpra i would like to work on this issue :)

**Comment by Aaishpra** [comment]
@Bhawna147 are you still interested in the issue or we can assign this to @satavshreya

**Comment by khushishikhu** [comment]
@satavshreya assigning this to you. As no one is currently working on this or responded in a while

**Comment by satavshreya** [comment]
@khushishikhu working on this now

**Comment by satavshreya** [comment]
These are the css changes i made do tell me if you need some more changes:
![image](https://user-images.githubusercontent.com/61575173/114135314-b803dd00-9926-11eb-97d6-0a1612eb9db5.png)
![image](https://user-images.githubusercontent.com/61575173/114135344-c0f4ae80-9926-11eb-98ad-8b1a01131ad5.png)

**Comment by Aaishpra** [comment]
Can you use the same font as navbar in those buttons?

**Comment by satavshreya** [comment]
@Aaishpra yes sure i will again put the screenshots

**Comment by satavshreya** [comment]
![image](https://user-images.githubusercontent.com/61575173/114136573-9146a600-9928-11eb-90ad-6c901de808e3.png)
is it okay now?

**Comment by Aaishpra** [comment]
Better now, go forward with a PR.
