### ISSUE TITLE
The content of footer

### ISSUE THREAD

**Issue by RuchiGitHu** [Feminine-Divine/periodo#260]
## Is your feature request related to a problem? Please describe.
The content of footer is aligned in center of screen, it should in bottom of the screen, so that anyone can understand that this is footer, also the background color of form and footer is same. That is why, it's difficult to assume that form is not a part of footer.

## Describe the solution you'd like
I want to push content in bottom of the page as footer content should not be in too upper side of website.

## Additional context
I think the background color of footer is also require to change for showing footer different like header.

**Comment by K-Kumar-01** [comment]
@RuchiGitHu 
A screenshot depicting the same would be better to understand.

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu
> A screenshot depicting the same would be better to understand.

I didn't understand what you want to say. Apologies for this....

**Comment by Aaishpra** [comment]
Hi, @RuchiGitHu @K-Kumar-01 means can you provide any screenshot or any image of the implementation you talked about in the issue
>The content of footer is aligned in center of screen, it should in bottom of the screen, so that anyone can understand that this is footer, also the background color of form and footer is same. That is why, it's difficult to assume that form is not a part of footer.

(this part) from any working website so that it will be easier for us to understand this issue.

**Comment by RuchiGitHu** [comment]
> Hi, @RuchiGitHu @K-Kumar-01 means can you provide any screenshot or any image of the implementation you talked about in the issue
> 
> > The content of footer is aligned in center of screen, it should in bottom of the screen, so that anyone can understand that this is footer, also the background color of form and footer is same. That is why, it's difficult to assume that form is not a part of footer.
> 
> (this part) from any working website so that it will be easier for us to understand this issue.

From this image, I am trying to say that footer should be look like footer not a part of website blocks. The content is also placed in below in the footer block. The background color is also helpful to show that this is a footer(end of the current page). Footer should be visible like header.
![image](https://user-images.githubusercontent.com/71754179/116898629-3caaf800-ac54-11eb-8e3b-a105dc182ce6.png)

**Comment by Aaishpra** [comment]
Sure thanks for clarifying I have assigned you here @RuchiGitHu
