### ISSUE TITLE
Change the navbar into sidebar or navigation drawer

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/periodo#261]
## Is your feature request related to a problem? Please describe.

The current navbar is bulky and not very geat looking
## Describe the solution you'd like

Change the navbar into a sidebar or more commonly navigation drawer.
## Additional context

Use material-UI for styling 
Checkout:
https://material-ui.com/components/drawers/
https://stackoverflow.com/questions/39865799/making-sidebar-with-material-ui

**Comment by Aaishpra** [comment]
@subhangi2731 will you be able to work here, if yes please comment here, I will assign this issue to you.
Thanks

**Comment by gnikita432** [comment]
I would like to work on this issue.

**Comment by subhangi2731** [comment]
@Aaishpra thank you so much for creating an issue for me. Yes I will work on this issue. please assign it to me.

**Comment by subhangi2731** [comment]
@gnikita432 u already made a pr on my issue in which I was assigned so thatswhy this issue she has created for me to be assigned.

**Comment by Aaishpra** [comment]
Great @subhangi2731 and no need to thank, it's contributors like you who are patient makes my work easier.
Happy coding
ping me if you face any doubts about working here.

**Comment by gnikita432** [comment]
@subhangi2731 Ohh I didn't know My apologies. All the best.

**Comment by subhangi2731** [comment]
@Aaishpra so kind of you. sure I will ping you if I have any doubts and I will raise a pr by tomorrow.

**Comment by subhangi2731** [comment]
@gnikita432 its okay. Thank you and same to you
