### ISSUE TITLE
Talk with us form UI enhancement.

### ISSUE THREAD

**Issue by Shivangi-ch** [Feminine-Divine/periodo#262]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
I would like to make the UI of the talk with us section and will make it more user friendly.

## Additional context
I am  a GSSOC participant.
PLease assign me this issue.

**Comment by Shivangi-ch** [comment]
@khushishikhu  the talk with us form can be approved .I will make it more user friendly also will apply so gradient colors to it.
Please give me a chance to do this.

**Comment by khushishikhu** [comment]
@Shivangi-ch  I liked your idea. If you want to go ahead with this I can assign you to this. thank you!

**Comment by Shivangi-ch** [comment]
@khushishikhu Yes.Please assign this to me.
