### ISSUE TITLE
Add floating animation in the svg(image) of the cards used in the about us section.

### ISSUE THREAD

**Issue by Shivangi-ch** [Feminine-Divine/periodo#263]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
I would like to add add floating animation in the svg(image) of the cards used in the about us section.this will make the page look attractive.

## Additional context
Demo of floating animation.
![doc2pen](https://user-images.githubusercontent.com/57783826/116885463-893b0700-ac45-11eb-80af-d36ca0e71b3c.gif)

**Comment by Aaishpra** [comment]
great go for it.
