### ISSUE TITLE
Navigation bar titles need to change

### ISSUE THREAD

**Issue by raks924** [Feminine-Divine/periodo#264]
## Is your feature request related to a problem? Please describe.
the navigation bar titles look too big and clustered 

## Describe the solution you'd like
i would like to either change the font or fontsize to make it look more pretty
![Screenshot (23)_LI](https://user-images.githubusercontent.com/68598387/116897470-e9847580-ac52-11eb-9d1e-6b0ef9a2e698.jpg)

**Comment by khushishikhu** [comment]
@raks924 go ahead

**Comment by raks924** [comment]
txxx
