### ISSUE TITLE
docs: Add the instruction

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#268]
## 📚 Documentation
Add the instructions about Rebasing the commits to the Contributing.md

**Comment by Khushi-24** [comment]
@khushishikhu Can I work on this?

**Comment by khushishikhu** [comment]
@Khushi-24 assigning this to you

**Comment by Khushi-24** [comment]
@khushishikhu I have made the changes have a look. Please tell, if the changes made aren't correct or any further changes are required.

**Comment by khushishikhu** [comment]
@Khushi-24 You have opened a PR in your forked repository instead of feminine-divine repository. please look at it again and send your PR

**Comment by Khushi-24** [comment]
@khushishikhu Sorry for the inconvenience. I corrected it.
