### ISSUE TITLE
coding: Link to Calendar in Navbar

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#27]
## Description
Add the Link to the Calendar page as well just like the "Home" is written over there as shown in the given picture and directs to that page 
![Capture](https://user-images.githubusercontent.com/65439761/110433227-2d854f00-80d6-11eb-97d2-5864072d4108.PNG)

**Comment by WaderManasi** [comment]
Hi @khushishikhu ,
I wish to work on the issue as a part of gssoc'21

**Comment by khushishikhu** [comment]
@WaderManasi assigning this to you. Happy Coding!!

**Comment by WaderManasi** [comment]
Thanks for assigning @khushishikhu !

**Comment by janvi01** [comment]
I would like to work on this issue.

**Comment by khushishikhu** [comment]
@janvi01 assigning this to you. Happy Coding!!

**Comment by WaderManasi** [comment]
@khushishikhu  Actually I was working on it!

**Comment by khushishikhu** [comment]
@WaderManasi you are already assigned in an issue. That's why I have assigned this to her, as we have to give chance to other participants also to contribute. When you are done with your issue. Then you can ask on any available issue of the project where no one is working or haven't given any updates. I hope you get it. Thank you for showing interest 😊

**Comment by WaderManasi** [comment]
Okay @khushishikhu ,
No issues ☺️
