### ISSUE TITLE
bug in wanna rate yourself page

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/61223163/117451014-94e93f00-af5f-11eb-9370-cf83e9d0b954.png)
I would like to solve this issue

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 assigning this to you
