### ISSUE TITLE
there is some error in the navbar.css code

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#274]
**Describe the bug**

There is one problem in the navbar component due to which the period app is unable to open and giving internal server error.
![image](https://user-images.githubusercontent.com/61223163/117578077-3f9d6100-b10a-11eb-9177-823a28c510dd.png)
I would like to solve this issue. Please assign it to me.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gnikita432** [comment]
@Shivangi-ch @mayank-khyrmai I have created the issue and I have too Fixed the issue.

**Comment by Aaishpra** [comment]
@gnikita432 send the PR
