### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by subhangi2731** [Feminine-Divine/periodo#276]
**Describe the bug**
Running npm run dev brings up an error Internal Server Error instead of the webpage

**To Reproduce**
1. Run npm
2. Run dev
3. See error

**Comment by subhangi2731** [comment]
please assign me this @khushishikhu I will fix the bug

**Comment by subhangi2731** [comment]
@Aaishpra please assign me this bug issue so that I can work further

**Comment by Aaishpra** [comment]
Were you on the right directory ie `cd periodo/periodo`  @subhangi2731 and the command `npm run dev` should be run on a single line after running `npm install` it's mentioned in the setup instructions

**Comment by subhangi2731** [comment]
@Aaishpra Yes I was on the right directory and I had run according to the setup instructions it shows internal server error let me share u the screenshot will that be okay?

**Comment by Aaishpra** [comment]
Ya sure and please share the screenshot of your terminal/git command shell(whatever you use) too,

**Comment by subhangi2731** [comment]
@Aaishpra There is a periodo bug

Syntax error: /home/periodo/periodo/components/navbar.css Unclosed block

![Screenshot from 2021-05-12 22-07-18](https://user-images.githubusercontent.com/53938490/118027045-1d604900-b37f-11eb-8cac-457528153202.png)

**Comment by subhangi2731** [comment]
I want to resolve this please assign me the issue @Aaishpra

**Comment by gnikita432** [comment]
Hey, @subhangi2731 you have created a duplicate issue. Please check issue #274

**Comment by subhangi2731** [comment]
@Aaishpra sorry for the inconvenience I will close this issue
