### ISSUE TITLE
All secret key are public

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#278]
**Describe the bug**
All the API keys are public,

**To Reproduce**

**Expected behavior**
They should not be visible in public, they need to be included in .gitignore file

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@garvitgupta13 Thank you for opening this issue
