### ISSUE TITLE
Apply form validation to talk us form

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#279]
## Is your feature request related to a problem? Please describe.
YES, currently if no one enters a value then also it will submit the form instead of that it should throw an error

## Describe the solution you'd like
Apply form validation

## Additional context
NO

**Comment by garvitgupta13** [comment]
Please assign this issue to me under gssoc21

**Comment by Aaishpra** [comment]
> Hey @Aaishpra please assign this issue to me under `gssoc21`

Assigned
