### ISSUE TITLE
coding: Link to Flow in Navbar

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#28]
## Description
Add the Link to the Flow page when a user click on the "Wanna Rate Yourself" (should be in Navbar) just like the "Home" is written over there as shown in the given picture and directs to that page
![Capture](https://user-images.githubusercontent.com/65439761/110433729-d92e9f00-80d6-11eb-9275-8fa214f8a602.PNG)

**Comment by Quickbeasts51429** [comment]
Can I be assigned the issue of making the nav bar  as well as adding links to it?

**Comment by khushishikhu** [comment]
@Quickbeasts51429 sure, assigning this to you. Happy Coding!!

**Comment by Quickbeasts51429** [comment]
thanks!!

**Comment by janvi01** [comment]
Can I work on this issue?

**Comment by janvi01** [comment]
@khushishikhu

**Comment by khushishikhu** [comment]
@janvi01 assigning this to you. Happy Coding!!

**Comment by janvi01** [comment]
where should I put "Wanna Rate Yourself" option, just after home option or at last or in between any two option?
Please elaborate

**Comment by janvi01** [comment]
@khushishikhu

**Comment by khushishikhu** [comment]
@janvi01 anywhere you can put. Where you feel it looks good

**Comment by janvi01** [comment]
@khushishikhu I have made PR, please check
