### ISSUE TITLE
Apply form-validation to Gynac help form

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#280]
## Is your feature request related to a problem? Please describe.
YES, currently if no one enters a value then also it will submit the form instead of that it should throw an error

## Describe the solution you'd like
Make them compulsory attribute

**Comment by Aaishpra** [comment]
assigned

**Comment by garvitgupta13** [comment]
Hey @Aaishpra please review my PR

**Comment by Aaishpra** [comment]
I have added some comments there. Please look at them and do the required changes @garvitgupta13 and if possible add a gif showing the changes

**Comment by garvitgupta13** [comment]
> I have added some comments there. Please look at them and do the required changes @garvitgupta13 and if possible add a gif showing the changes

Hey @Aaishpra I have made the changes you have requested
I don't have much idea about gif but instead of that I have pasted screenshots where ever possible
