### ISSUE TITLE
Clean the code.

### ISSUE THREAD

**Issue by Shivangi-ch** [Feminine-Divine/periodo#282]
**Describe the bug**

- Due to a lot of contributions, the code is messy right now. For example improper indentation, unesseccary spaces/tabs, lack of comments to explain the code and extra commented code.
- All this makes it difficult for beginner contributors to understand the code.
- So the code should be cleaned.

**Additional context**

Please assign it under `Gssoc21`.
@khushishikhu @Aaishpra

**Comment by Aaishpra** [comment]
Great go for it
