### ISSUE TITLE
styling about section for mobile view

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#284]
**Describe the bug**

![image](https://user-images.githubusercontent.com/61223163/118155702-24965e00-b436-11eb-81eb-cc6943a3fbee.png)
As the headings and paragraph are not in em or rem they are not changing their size accordingly and also there is no padding or margin in the left and right side.
I would like to improve this.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 Go ahead
