### ISSUE TITLE
Footer text gets aligned to left for screen size less than or equal to 320px

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#285]
**Describe the bug**

![image](https://user-images.githubusercontent.com/61223163/118156470-041ad380-b437-11eb-8590-af5eb165da1e.png)
Footer is not responsive for screen size less than or equal to 320px. I would like to work on this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 go ahead
