### ISSUE TITLE
coding: Create Navbar

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#29]
## Description
Create the Navbar on the Flow page also just like the Navbar on the other Pages of the website

**Comment by Quickbeasts51429** [comment]
@khushishikhu  ,This would be my first contribution in GSSOC'21 so can I be assigned the issue to work upon?
i would be delivering efficient work in minimal time.

**Comment by khushishikhu** [comment]
@mdPial as that PR is approved and we will merge it shortly. So yes now you can work on this issue.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by mdPial** [comment]
@khushishikhu I am little confused. Did you mean to add the Navbar component or to create a new one?. :sweat_smile:
