### ISSUE TITLE
 Blue color in the navbar

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#291]
**Describe the bug**

The blue color in the navbar is not looking according to the theme of the website.
I would like to changes its color to black.
![image](https://user-images.githubusercontent.com/61223163/118358867-6e01bd00-b59e-11eb-9da8-0bcf5f7116cb.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432  Thank you so much for opening this issue. I was about to open it. Also on some pages, the upper portion isn't visible correctly. Please resolve that too

**Comment by gnikita432** [comment]
Okay sure. Thank you for assigning.
