### ISSUE TITLE
Navbar is overlapping the heading of all the pages.

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#292]
**Describe the bug**

The navbar is overlapping the heading of the tips section.
![image](https://user-images.githubusercontent.com/61223163/118358970-ccc73680-b59e-11eb-8f2b-481a73bda57c.png)
![image](https://user-images.githubusercontent.com/61223163/118359123-98a04580-b59f-11eb-9c86-5145098dc159.png)

I would like to fix this issue.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432  Correct all these things in the previous issue  you have opened as I have told there.

**Comment by gnikita432** [comment]
Okay Sure, Thank you. I will close this issue.
