### ISSUE TITLE
Social Media icons

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#295]
## Is your feature request related to a problem? Please describe.
I want to add social media icons at the home page (which is on footer) on the left side  because in footer it doesn't look nice and the home page is also simple. And also want to add hove effect. 
like:-
![118266222-c03fc280-b466-11eb-8f4c-bc2327c6c2d8](https://user-images.githubusercontent.com/69043944/118371544-8bf8fe80-b559-11eb-82f2-e6d13be27672.png)
![InkedPeriodo App - Personal - Microsoft​ Edge 5_15_2021 10_03_03 PM_LI](https://user-images.githubusercontent.com/69043944/118371557-92877600-b559-11eb-9dd7-8d06126f8a37.jpg)
![InkedPeriodo App - Personal - Microsoft​ Edge 5_15_2021 10_03_17 PM_LI](https://user-images.githubusercontent.com/69043944/118371565-99ae8400-b559-11eb-9920-3dca2be8ea37.jpg)

**Comment by kumarishalini6** [comment]
Can I work on this issue under GSSoC'21 participant.

**Comment by Aaishpra** [comment]
Great!! Go for it.

**Comment by Aaishpra** [comment]
But please add them to the right side of the site We have our navbar on the left now

**Comment by kumarishalini6** [comment]
sure

**Comment by kumarishalini6** [comment]
Merged

**Comment by kumarishalini6** [comment]
Merged
