### ISSUE TITLE
Navbar on Login/Signup/Forget password  page

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#299]
## Is your feature request related to a problem? Please describe.
I have seen there is no navbar in login, signup and forget password page . I guess there should be navbar.
I want to work on this issue under GSSoC'21.
![Log in to Periodo - Personal - Microsoft​ Edge 5_16_2021 12_48_07 PM](https://user-images.githubusercontent.com/69043944/118389052-812f7f80-b5d4-11eb-8733-dd384f846ec4.png)
21.

**Comment by khushishikhu** [comment]
@kumarishalini6 I don't think that we have all those kind of pages. We just have a signup page

**Comment by kumarishalini6** [comment]
Yes this is a single page sorry , just editing it

**Comment by khushishikhu** [comment]
actually, this is autogenerated page you can not edit it

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
if editing is not possible then close this issue
