### ISSUE TITLE
Feat: Modify the "Tap Here" button

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#3]
## Description
Modify the Tap Here button of the homepage

**Comment by Shwetang550** [comment]
I can make a much suitable "Tap here" button for this site... Please assign this to me :)

**Comment by khushishikhu** [comment]
@Shwetang550 Sure, assigning it to you. Happy Coding!!

**Comment by Artistic18** [comment]
@Shwetang550 are you still working on this issue?

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by Shwetang550** [comment]
@Artistic18 yess... Am still working on it :)
