### ISSUE TITLE
Feat: Creating a decent footer for website.

### ISSUE THREAD

**Issue by WaderManasi** [Feminine-Divine/periodo#30]
Hi @khushishikhu ,
A decent footer can  be added to the website containing links to the github source code, and organization name.
As a part of gssoc'21 I would like to work on it.

**Comment by Quickbeasts51429** [comment]
hi can I take take up the task and start working on it? I'll be looking towards good details too.

**Comment by Riya764** [comment]
I would like to work on this issue as a GSSoC'21 participant

**Comment by WaderManasi** [comment]
Hi, @khushishikhu ,@Aaishpra
This is prototype of footer for the website. Just approve once so that I will write code for the same and let me know if you have more suggestions.
Thank you!
![footer](https://user-images.githubusercontent.com/52437677/110795618-0f1d8000-829d-11eb-9d98-c692960dfa35.png)

**Comment by khushishikhu** [comment]
@WaderManasi  I liked it a lot the way you design it . Please go for making the PR and show us the screenshot of whole page with the footer .

**Comment by Aaishpra** [comment]
Good to go from my side too 💯

**Comment by WaderManasi** [comment]
Since, background of website is pink, I have changed shade of pink to darker one ,with alignment changes
![ss](https://user-images.githubusercontent.com/52437677/110834289-620a2e00-82c3-11eb-9ed7-4c36f8e2b80e.PNG)

**Comment by WaderManasi** [comment]
I have created the PR.

**Comment by 0Faiz0** [comment]
I Would like to work on this issue as a GSSOC'21 participant.

**Comment by RituCs** [comment]
Hello, I would like to work on this issue . The footer section needs improvements in its design and should be more informative like open source section,follow us section,copyright . Thanks !
