### ISSUE TITLE
Bug in Calendar Responsiveness

### ISSUE THREAD

**Issue by Saatvik21** [Feminine-Divine/periodo#302]
**Describe the bug**

**To Reproduce**
1. Go to 'Calender'
2. Resize it below 768px till 400px 

**Expected behavior**
The background of the calendar does not cover up the whole calendar text

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/61618767/118398993-a4136f80-b678-11eb-9837-1eb0ba7a6f58.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : chrome

**Smartphone (please complete the following information):**

**Additional context**
I would like to improve the responsiveness of the calendar page. Kindly assign me this issue under gssoc'21

**Comment by khushishikhu** [comment]
@Saatvik21 go ahead
