### ISSUE TITLE
Improving navbar

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#303]
## Is your feature request related to a problem? Please describe.
The color of navbar is black and the color of side navbar is white but their colour should be according to theme of the project (pink or shades of pink) . I want to work on this issue under GSSoC'21 participant.

**Comment by kumarishalini6** [comment]
![Periodo App - Personal - Microsoft​ Edge 5_16_2021 11_37_16 PM](https://user-images.githubusercontent.com/69043944/118410734-6c3b0680-b63d-11eb-8450-f81279e8d246.png)

**Comment by khushishikhu** [comment]
@kumarishalini6 go ahead

**Comment by kumarishalini6** [comment]
Thanks
