### ISSUE TITLE
Bug in gynac help page

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#304]
**Describe the bug**

The gynac help page is not responsive for mobile view
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/61223163/118425309-8c72d000-b6e6-11eb-9059-9a59750759a5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432  This issue is already opened #254
