### ISSUE TITLE
The text in about us page is hard to read

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#309]
**Describe the bug**

![image](https://user-images.githubusercontent.com/61223163/118451090-7f6bd600-b712-11eb-8dc5-29bb2bfaeaf7.png)
I would like to change the text style so that it will be more visible.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 Go ahead
