### ISSUE TITLE
Text in navbar is very light

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#310]
**Describe the bug**

Text in navbar is very thin and difficult to read

**To Reproduce**

**Expected behavior**

We can enhance the font-style of the navbar elements and make it more easy to read

**Screenshots**

![image](https://user-images.githubusercontent.com/70805691/118472129-1db56700-b726-11eb-9097-3b77081dc297.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@garvitgupta13  Go ahead
