### ISSUE TITLE
Added features in Tips page

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#312]
## Is your feature request related to a problem? Please describe.
I have seen the Tips page , by seeing that page I thought there should be added 2,3 .
1) How to use napkin,
2)Which napkin should,
3)Time to change Napkin
4)Things Avoid during periods
5)Things to do in periods (existing )

I want to make Tips with new style :- 
When someone open that page there should be buttons (all the topics button maintained above) related  to what they want to,
on clicking on buttons the tips page open. And there also be a back button to get back .

I want to work on this issue Under GSSoC'21.

**Comment by khushishikhu** [comment]
@kumarishalini6  Go ahead

**Comment by kumarishalini6** [comment]
@khushishikhu  I need your help, can you please tell me how to implement new page I am not able to found the app.js file.

**Comment by kumarishalini6** [comment]
And where is error page

**Comment by kumarishalini6** [comment]
@khushishikhu  i have made front page can u please tell me is it ok or need some changes
![Periodo App - Personal - Microsoft​ Edge 5_20_2021 12_25_50 PM](https://user-images.githubusercontent.com/69043944/118933437-ab937c80-b8f5-11eb-9aed-de06d4c8a17b.png)

**Comment by kumarishalini6** [comment]
sorry i am late because of my internals , i hope you'll understand.
