### ISSUE TITLE
Restroom and chat button is overlapping some content in mobile view.

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#319]
**Describe the bug**

![image](https://user-images.githubusercontent.com/61223163/118647628-2ded4500-b7ff-11eb-8931-d06c19ef8c3f.png)
I would like to place the restroom and chat button at an equal level from the bottom and side.
And make the content visible which is now overlapping.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 go ahead
