### ISSUE TITLE
About us page section 

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#330]
## Is your feature request related to a problem? Please describe.
I have seen in about us section their is "HOW WE HELP " section not look good because of background color (black) because it matches with the logo and need to change font family. I want to work on this issue under GSSoC'21.
![InkedAbout - Personal - Microsoft​ Edge 5_20_2021 04_01_18 PM_LI](https://user-images.githubusercontent.com/69043944/118964938-895d2700-b914-11eb-8e85-5add335954cc.jpg)

**Comment by kumarishalini6** [comment]
@khushishikhu  thanks for the last issue and please assign me this issue I really want to improve it.

**Comment by khushishikhu** [comment]
@kumarishalini6 I don't think that it is a valid issue

**Comment by kumarishalini6** [comment]
Ok , no problem
