### ISSUE TITLE
FAqs section in navbar

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#334]
## Is your feature request related to a problem? Please describe.
There should be a section in navbar FAqs for the period beginner girls and for the others too.

**Comment by kumarishalini6** [comment]
Can I work work on this issue under GSSoC'21 participant.

**Comment by kumarishalini6** [comment]
@khushishikhu

**Comment by khushishikhu** [comment]
@kumarishalini6 assigned
