### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by encodeArnab** [Feminine-Divine/periodo#34]
I want to improve the UI for this website,
it is very difficult for a person to navigate across different sections.
I will be using **Figma** for this task and will work on the codes for the same if assigned.
When the design is accepted I will be using HTML, CSS and JS to build the website from scratch.
It would be a great learning experience for me by working on this open source projects.
Thank You

**Comment by encodeArnab** [comment]
I am a participant in GSSOC'21. If the idea is good for the project, please assign it to me; if it isn't, please tell me what needs to be changed and I can work on it. 
Should I close this issue if it isn't necessary? 
Thank you very much.

**Comment by khushishikhu** [comment]
@encodeArnab The website is already built with the framework of Nextjs. So we don't think that it is currently required for the website. If you have some other ideas for the website feel free to open the issue for it. We appreciate your time and efforts.

**Comment by encodeArnab** [comment]
Okay Thank You for your suggestion I am closing this issue then.
