### ISSUE TITLE
Quiz page is not responsive

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#341]
**Describe the bug**

Quiz page breaks in mobile view

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/70805691/119237573-2a3d2380-bb5b-11eb-9aba-09e2fa45aadd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@garvitgupta13 assigned you
