### ISSUE TITLE
Tips section is not responsive

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#349]
**Describe the bug**

I would like to make the tips page responsive 
![image](https://user-images.githubusercontent.com/61223163/119351985-c03d8f00-bcbe-11eb-89f6-162acc5ed42a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushishikhu** [comment]
@gnikita432 assigned
