### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#353]
I want to make a timer to check blood flow. There is a clock and buttons start, stop, reset . 
I want to add these features in calander page when someone open that page there will be 2 option of timer and calander . 
I want to work on this issue under GSSoC'21 participant.

**Comment by kumarishalini6** [comment]
@khushishikhu please assign this issue to me.

**Comment by khushishikhu** [comment]
@kumarishalini6 assigned
