### ISSUE TITLE
Add hover effect to the PERIODO text in footer

### ISSUE THREAD

**Issue by tanishq-arya** [Feminine-Divine/periodo#356]
## Is your feature request related to a problem? Please describe.
Add hover effect similar to other icons in footer.
![image](https://user-images.githubusercontent.com/77333275/119453062-a8b0e580-bd54-11eb-873e-f7a24eec3e1d.png)

**Comment by tanishq-arya** [comment]
Please assign me this issue.

**Comment by tanishq-arya** [comment]
Like this
![image](https://user-images.githubusercontent.com/77333275/119478583-8aa3af00-bd6d-11eb-85ba-41ce209eb908.png)

**Comment by khushishikhu** [comment]
Assigned
