### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by tanishq-arya** [Feminine-Divine/periodo#358]
## 📚 Documentation

The introduction para on top is clustered. I can improve upon the text and make it look better.

The code segments in readme with comments are confusing. Single commands are much more clear and faster to understand. I would like to update the installation and setup part.

**Comment by tanishq-arya** [comment]
@khushishikhu Please assign me this issue.

**Comment by khushishikhu** [comment]
@tanishq-arya assigned
