### ISSUE TITLE
Contact Form not Responsive

### ISSUE THREAD

**Issue by Saatvik21** [Feminine-Divine/periodo#366]
**Describe the bug**
The comments text area in the contact form is not properly aligned with other text inputs as it's width decreases when the screen size decreases below 1000px. Also the submit button is not centered in screen size below 1000px.

**To Reproduce**

**Screenshots**
![Screenshot_7](https://user-images.githubusercontent.com/61618767/119655683-7df38980-be47-11eb-9b30-6e472f84615a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to fix this issue, Kindly assign me @khushishikhu

**Comment by khushishikhu** [comment]
@Saatvik21 Assigned
