### ISSUE TITLE
overlapping in quiz page

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#380]
![Periodo App - Personal - Microsoft​ Edge 5_28_2021 07_18_01 PM_LI](https://user-images.githubusercontent.com/69043944/119994740-57ce0680-bf79-11eb-96ab-520815ca5fe6.jpg)

Can i work on this issue ??
@khushishikhu

**Comment by khushishikhu** [comment]
@kumarishalini6 go ahead
