### ISSUE TITLE
Social Campaign not Responsive

### ISSUE THREAD

**Issue by Saatvik21** [Feminine-Divine/periodo#381]
**Describe the bug**
The social campaign page is not responsive.

**To Reproduce**

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/61618767/120010596-f2baf500-bffa-11eb-9049-a114d5d22433.png)
![Screenshot_2](https://user-images.githubusercontent.com/61618767/120010607-f484b880-bffa-11eb-9846-59d589dc213e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to fix this issue. Kindly assign me @khushishikhu

**Comment by khushishikhu** [comment]
@Saatvik21 assigned
