### ISSUE TITLE
Video section in navbar

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#383]
There should be a section of video in navbar for those who don't want to read the document . I want to make that section.
Can I work on this issue under GSSoC'21 participant.

@khushishikhu  please assign this issue to me

**Comment by kumarishalini6** [comment]
@khushishikhu  can you please assign this issue to me

**Comment by khushishikhu** [comment]
@kumarishalini6  we don't want such thing in our project instead of you can add the images(two girls images in the style.home.css file) in the website which is not visible back then, if you like you can look for that bug

**Comment by kumarishalini6** [comment]
Your are taking about the background image of 2 girls??

**Comment by kumarishalini6** [comment]
I am not getting it can you please explain it

**Comment by khushishikhu** [comment]
@kumarishalini6 yeah the background image

**Comment by kumarishalini6** [comment]
@khushishikhu I love to do the change but it will be easy for me if you tell me what changes you want .
