### ISSUE TITLE
Logo of Social Campaign

### ISSUE THREAD

**Issue by Saatvik21** [Feminine-Divine/periodo#388]
## Is your feature request related to a problem? Please describe.

Currently, there is no logo for social campaigns in the sidebar. Also, the spelling of campaign is wrong.

![Screenshot_8](https://user-images.githubusercontent.com/61618767/120078500-80ffab80-c0cd-11eb-8fda-36e9cc35d683.png)

## Describe the solution you'd like

I would like to fix this issue @khushishikhu.

**Comment by Saatvik21** [comment]
Please assign me @khushishikhu

**Comment by khushishikhu** [comment]
assigned
