### ISSUE TITLE
Make rate yourself page responsive

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#389]
**Describe the bug**

Rate yourself page is not responsive
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/70805691/120083070-e78fc400-c0e3-11eb-8e14-8e84f25a6bf4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please assign me this issue under `gssoc21`

**Comment by khushishikhu** [comment]
assgned
