### ISSUE TITLE
Coding : Creating an image slider for the landing page.

### ISSUE THREAD

**Issue by shalmoly79** [Feminine-Divine/periodo#39]
Hello, I am a GSSOC'21 participant. I want to create a simple image carousel. It should contain arrows on each side to advance the image forward or backward and I will add some other functionalities like the images should automatically move forward after a certain time. This will make the website more visually appealing. If you find this issue helpful please assign me for this contribution. Thanking you in advance.

**Comment by shalmoly79** [comment]
Thank you so much. Working on it.

**Comment by Aaishpra** [comment]
@shalmoly79 updates??
