### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by garvitgupta13** [Feminine-Divine/periodo#391]
**Describe the bug**

Remove the extra space between contact us form and FAQs
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/70805691/120083216-ba8fe100-c0e4-11eb-919b-d8cbb863e235.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Please assign me this issue under `gssoc21`

**Comment by khushishikhu** [comment]
assigned

**Comment by garvitgupta13** [comment]
> assigned

@khushishikhu pleases review the PR
