### ISSUE TITLE
A page which shows information about various products that can be used when a female is menstruating

### ISSUE THREAD

**Issue by gnikita432** [Feminine-Divine/periodo#392]
## Is your feature request related to a problem? Please describe.

I would like to add a page that shows information about various products that women can use during their periods like pads (or sanitary napkins), tampons, menstrual cups, etc
## Additional context

@Aaishpra @khushishikhu Can you please assign me this issue.

**Comment by khushishikhu** [comment]
@gnikita432  These all things are added in Tips
