### ISSUE TITLE
Animated Heading

### ISSUE THREAD

**Issue by drishtipeshwani** [Feminine-Divine/periodo#40]
Hello ! I am a Drishti, I am a GSSOC Participant I would like to make the heading "Hi Girls, wanna track your periods!!" more attractive by enhancing its CSS and implement text typing animation effect.
Do assign this issue to me.
Thanks in Advance.

**Comment by khushishikhu** [comment]
@drishtipeshwani  Assigning this to you. Thank You for opening this issue.

**Comment by drishtipeshwani** [comment]
Thankyou Started working on it !
