### ISSUE TITLE
Bug FAQs page 

### ISSUE THREAD

**Issue by kumarishalini6** [Feminine-Divine/periodo#400]
The tip page is responsive but there is no margin left at the top and bottom because of that the text written at the top and the contact us , footer is overlapped by them.
![Periodo App - Personal - Microsoft​ Edge 5_31_2021 06_27_03 AM](https://user-images.githubusercontent.com/69043944/120126279-426aff00-c168-11eb-94d6-134a285b1498.png)
![Periodo App - Personal - Microsoft​ Edge 5_31_2021 06_27_20 AM](https://user-images.githubusercontent.com/69043944/120126289-49920d00-c168-11eb-8ca2-8b893b31c112.png)

**Comment by kumarishalini6** [comment]
@khushishikhu  can I work on this issue

**Comment by khushishikhu** [comment]
Go ahead
