### ISSUE TITLE
Styling the Rating Labels

### ISSUE THREAD

**Issue by sayna3311** [Feminine-Divine/periodo#44]
The rating labels can be styled more and the alignment can also be corrected. If accepted, I would like to work on this issue.

**Comment by khushishikhu** [comment]
@sayna3311 Thank you for opening this issue. Assigning this to you

**Comment by sayna3311** [comment]
It was like this earlier.
![image](https://user-images.githubusercontent.com/67572440/110761949-504e6980-8276-11eb-873f-34557f683df8.png)



And I have changed it like this.
![image](https://user-images.githubusercontent.com/67572440/110762470-d2d72900-8276-11eb-80af-4eab74d37841.png)

**Comment by sayna3311** [comment]
Shall I send the PR?
