### ISSUE TITLE
README.md: name of the application is wrong in About Section

### ISSUE THREAD

**Issue by Ishikakhurana** [Feminine-Divine/periodo#45]
hey @khushishikhu there is a spelling error in About Section in 3rd line. Also About Section mentions first period as facing some problem but isn't period something natural. Maybe it can be replaced from facing period to experiencing first periods?

**Comment by Aaishpra** [comment]
@Ishikakhurana you can work on the content of the About section of Readme (be it changing the content or correcting spelling mistakes) just send a PR and we can review it.

**Comment by vismitap** [comment]
Hey! May I work on this issue?

**Comment by khushishikhu** [comment]
@vismitap assigning this to you. Happy Coding!!

**Comment by vismitap** [comment]
Hey @khushishikhu, what happened? May I work on this?

**Comment by khushishikhu** [comment]
@vismitap actually this issue has already been done so now I am closing this issue. Sorry for inconvenience 😅
