### ISSUE TITLE
coding: Create a page for adding notes

### ISSUE THREAD

**Issue by JASHANJOT7KAUR** [Feminine-Divine/periodo#49]
I would like to redesign the homepage to be more user-friendly and interactive.
I also would like to add "add note" feature for some important notes the user wants to make.

**Comment by aashishah** [comment]
I'd like to work on this issue as well, I have experience with making smooth flowing responsive websites. Please let me know if it would be  possible for me to work on this!

**Comment by khushishikhu** [comment]
@JASHANJOT7KAUR  Not on the homepage. If you want to add this feature, you can make another page on the Website for this feature. If you can do that. I am assigning this to you.

**Comment by subhangi2731** [comment]
I also want to work on this. can you please assign me too

**Comment by haarsh01** [comment]
Hello I am 'a participant of GSSoC'21
I can contribute to this issue. 
Please assign me this task
Thank you!

**Comment by khushishikhu** [comment]
@subhangi2731  if you are willing to do this issue? Then I can assign this to you

**Comment by SandeepKrSuman** [comment]
If no one is up for it, I can take this...

**Comment by khushishikhu** [comment]
@SandeepKrSuman  assigning this to you. Happy Coding!!
