### ISSUE TITLE
coding: design the About page

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#5]
## Description
Design the About page on figma and discuss it with mentors

**Comment by kunal299** [comment]
@khushishikhu Could you plz assign this issue to me as a part of Gssoc'21?

**Comment by A-HK** [comment]
Hey @khushishikhu , if it hasn't been assigned yet, can you please assign this issue to me under the GSSoc'21 program?
I have previous experience with designing on Figma.

**Comment by khushishikhu** [comment]
@A-HK Sure, assigning this to you. Happy coding!!

**Comment by codebuzzer01** [comment]
Hey if it hasn't been worked on yet please assign it to me. @khushishikhu

**Comment by A-HK** [comment]
Hi @khushishikhu , this is the link of the draft of the Figma design I worked on:
https://www.figma.com/file/QKO2yLpr19h7XmO5EdBl83/PERIODO-ABOUT-US-PAGE?node-id=0%3A1
Let me know what you think ! ( All suggestions / criticisms are welcome :) )

**Comment by khushishikhu** [comment]
@A-HK Thank you so much for your efforts. This design looks amazing!! 
Let's take a view from @Aaishpra also

**Comment by Aaishpra** [comment]
@A-HK loved both the content and design 🚀, it's beautiful.
If you can include more colours(not just pink) like something similar to the homepage, it would be great.

**Comment by A-HK** [comment]
@khushishikhu @Aaishpra made a few changes with colours taken from the website homepage.
https://www.figma.com/file/QKO2yLpr19h7XmO5EdBl83/PERIODO-ABOUT-US-PAGE?node-id=0%3A1
If everything is fine, let me know if I should make a PR.

**Comment by Aaishpra** [comment]
@A-HK the design looks perfect now🚀send a PR after implementation of this page and we will review it once we get some time.
Again thanks for the design and content it is better than what i expected🤗

**Comment by A-HK** [comment]
Awesome! 
Sorry for the incessant questions, but should I implement this using HTML+ CSS or Next.js?

**Comment by Aaishpra** [comment]
Since the project is using nextjs it will be better to implement the page using Nextjs. And if you face any problems with the framework ping any of us we will help you.

**Comment by A-HK** [comment]
Hey @khushishikhu @Aaishpra , sorry for taking so much time!
I've never worked with Nextjs before, so exactly copying the design is proving to be a little tricky
![Screenshot (390)](https://user-images.githubusercontent.com/73497800/111303363-71e69100-867a-11eb-9d65-1e14f7a799fa.png)
Can you tell me if what I've worked on till now is acceptable?

**Comment by khushishikhu** [comment]
@A-HK  It's really awesome. Just one thing can you please change the colour of cards just like you showed us on your figma file

**Comment by A-HK** [comment]
Hey! Unfortunately, that's exactly what I'm not able to figure out.
If you don't mind, can I send a PR so that you can see my code and tell me where I'm going wrong?

**Comment by Aaishpra** [comment]
@A-HK yes please, also I am very glad that you learned working with next js for this PR, hope this was a good learning experience for you 😉.

**Comment by A-HK** [comment]
I sure did! This was extremely fun, although I suspect I messed up quite a bit xD.
