### ISSUE TITLE
Improve the rating page.

### ISSUE THREAD

**Issue by padmajabhol** [Feminine-Divine/periodo#54]
![Screenshot (17)](https://user-images.githubusercontent.com/75530516/110762014-5e9c8580-8276-11eb-8ded-f77d0da7b0ff.png)
I d love to improve this page, please assign it to me.

**Comment by Lza-etc** [comment]
Hi 
I would really like to contribute to this page. 
Would you assign me to solve this issue.

**Comment by Jimmy5467** [comment]
I am willing to solve this issue if you permit
