### ISSUE TITLE
feat:  About section in Navbar

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#6]
## Description
Add the about section in the navbar of the homepage

**Comment by kunal299** [comment]
@khushishikhu I would love to contribute to this issue. Could you plz assign this to me as a part of gssoc'21?

**Comment by bhavyashukla16** [comment]
Can u assign this issue to me?

**Comment by khushishikhu** [comment]
@bhavyashukla16 assigning this to you. Happy Coding 😊

**Comment by aashi2912** [comment]
I would like to work on this issue.

**Comment by lakshita15** [comment]
I'am gssoc participant 
I would like to work on this issue. I will submit before due date with fantastic work.
