### ISSUE TITLE
Code: Handling Accesibility

### ISSUE THREAD

**Issue by gaulghost** [Feminine-Divine/periodo#64]
I would like to work on the website for improving accessibility for color blinds, old age people & autoreaders or robots. I would like to participate in this issue as gssoc 2021 participant.

**Comment by khushishikhu** [comment]
@gaulghost I like this concept but how would you that. Can you please give us any prototype for implementing this.

**Comment by gaulghost** [comment]
I will implement tab order for the screen readers for easy follow through of the text, marking of links so that automatic / robotic web crawlers don't / do crawl the given link, Providing proper meta tags for better search as such for better google indexing, providing aria tags. Lastly providing alt text to images or links for better understanding of users and crawlers. Colour changes for better contrast, helpful to colour blind. This can also be seen in my website -      . If you wish, I will take 3-4 days to build my proposal  and submit. You can peruse it and decide on merging it or if required, suggest changes which I will implement.
