### ISSUE TITLE
coding: Display a dailog box 

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#66]
## Is your feature request related to a problem? Please describe.
When a user click on next button on the Calendar page. Display a Dailog box for confirmation. If the want to move on the next page or not

**Comment by SandeepKrSuman** [comment]
Hey @khushishikhu , I want to work on this. Can you please assign this to me.

**Comment by khushishikhu** [comment]
@SandeepKrSuman assigning this to you. Happy Coding!!

**Comment by SandeepKrSuman** [comment]
Thankyou.
