### ISSUE TITLE
Styling the button "tap here" and giving typing effect to "tagline"

### ISSUE THREAD

**Issue by ankitaugale23** [Feminine-Divine/periodo#68]
## Is your feature request related to a problem? Please describe.
1. As per the website the button will look good if it will match the color codes of the website
2. Tagline of the website looks great but after giving typing effect it will look more attarctive.

**Comment by ankitaugale23** [comment]
I would like to work on this. If I can please assign this to me @khushishikhu @Aaishpra

**Comment by rupal11** [comment]
I can style the "tap here" button using bootstrap classes. [https://rupal11.github.io/diceRoll/](url)
 is the URL of my website in which I have designed a similar kind of button. Please Assign this to me.

**Comment by Aaishpra** [comment]
@ankitaugale23 it's a duplicate issue we already have a new button and a pr for typing effect  of text.

**Comment by ankitaugale23** [comment]
oh okay. Thanks for letting me know.
