### ISSUE TITLE
Feat: Implement Dark Mode

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#69]
## Description
Implement the Dark Mode feature in the website

## Additional context
Must add the screenshot of how it will look like.

**Comment by Nidhikamewar15** [comment]
@khushishikhu  I would like to work on this. Can you please assign this to me?

**Comment by Shwetang550** [comment]
Hey @khushishikhu If @Nidhikamewar15 is not assigned this issue... Please assign it to me... I can make a toggle switch button to switch between dark and light mode :)

**Comment by khushishikhu** [comment]
@Shwetang550 assigning to you. @Nidhikamewar15 you are currently assigned to an issue. So I Can't assign you right now. When you are done with that please look on other issues in the project where people assigned pr haven't given any updates. Thank you for taking interest. Hope this helps ☺️

**Comment by Shwetang550** [comment]
Thank you @khushishikhu 😊

**Comment by mdPial** [comment]
@Shwetang550 Did you start working?

**Comment by khushishikhu** [comment]
@Shwetang550 any updates? Or I will assign this issue to @Nidhikamewar15 (if you are interested to work on it I will happily assign you 😊)

**Comment by Shwetang550** [comment]
Yess @mdPial I'm working on it...

Sorry @khushishikhu for the delay... Was busy in my mid-semester examinations 😅 will create a pr soon for this issue... 😁

**Comment by khushishikhu** [comment]
@mdPial No problem ✌️ I can understand

**Comment by Shwetang550** [comment]
Sorry @khushishikhu will be unable to pursue further because of some college stuff... You can assign this issue to someone else... Sorry for the inconvenience

**Comment by RituCs** [comment]
I would like to work on this issue under GSSOC'21. Please assign me. Thanks !

**Comment by khushishikhu** [comment]
@RituCs assigning this to you

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu  I am ready to  work on this!

**Comment by Aaishpra** [comment]
@Shwetang550 are you working here?

**Comment by satavshreya** [comment]
Do let me know @Aaishpra

**Comment by Aaishpra** [comment]
Sorry i guess i tagged wrong person @RituCs are you working here or we can assign this to @satavshreya

**Comment by satavshreya** [comment]
Do let me know @Aaishpra

**Comment by Aaishpra** [comment]
Go for it @satavshreya 🙌🏻

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu  I have a Question that which is the file that has been imported in every page because i want to add the darkmode and then just it has to be imported else i will have to make a new one :) Do let me know asap

**Comment by Aaishpra** [comment]
@khushishikhu can tell you that😅

**Comment by khushishikhu** [comment]
@satavshreya [This](https://github.com/Feminine-Divine/periodo/blob/master/periodo/styles/globals.css) is the file that is to be seen on every page and the background is from global.css file that is why we see the same background on every page

**Comment by satavshreya** [comment]
@khushishikhu where should i write js code then?

**Comment by satavshreya** [comment]
@khushishikhu  please let me know which file to write because i have got the css file but not js :)

**Comment by khushishikhu** [comment]
@satavshreya  there isn't any js file for the background that is designed because changes were made globally in css file. Maybe if you have any other idea to implement please share with us

**Comment by satavshreya** [comment]
@khushishikhu  actually for dark mode in every page there is a js code too that has to be implemented Now what i am thinking is  to create a new file just for dark mode but then you will have to import it on every page will that be okay???? And also in the dark mode the background will be changed because the background that we have is just a picture right so a dark picture having relevant background picture that we have i will have to find that one so that is what  in my mind do let me know what else you want with it!!

**Comment by khushishikhu** [comment]
@satavshreya I have got what you are trying to say. kindly refer to this article as well https://www.carlrippon.com/implementing-dark-mode-in-a-react-app-with-css-properties/

**Comment by subhangi2731** [comment]
@Aaishpra please assign me

**Comment by subhangi2731** [comment]
@khushishikhu please assign me so that I can start working
