### ISSUE TITLE
Coding: Make the website more responsive

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/periodo#7]
## Description
Currently the website doesn't looks good in small screen view

## Solution
Make it responsive enough smartphone screen, by adding correct margin, padding and mobile only view.

**Comment by mdPial** [comment]
I would like to work on that issue under GSSOC!

**Comment by sayna3311** [comment]
I would love to work on it, please assign this to me :)

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC.

**Comment by khushishikhu** [comment]
@nandini7637 assigning this to you. Happy Coding!!

**Comment by Chaitalishetty** [comment]
Hi I would like to work on this issue under Gssoc

**Comment by khushishikhu** [comment]
@Chaitalishetty assigning this to you. Happy Coding!!

**Comment by flyingsonu122** [comment]
@khushishikhu I can make it responsive for all screen sizes

**Comment by khushishikhu** [comment]
@flyingsonu122 Yes You can

**Comment by flyingsonu122** [comment]
> @flyingsonu122 Yes You can

@khushishikhu Assign this to me, so I can go ahead
