### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohank2502** [Feminine-Divine/periodo#71]
## 📚 Documentation

I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by khushishikhu** [comment]
@rohank2502 where You are planning to add the tech stack logo. please give us the brief issue description

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 where You are planning to add the tech stack logo. please give us the brief issue description

Hey Rohan here !!  Sorry for the delay So many issues where assigned I forget to look up the comments of non assigned issue ok so I will like to show you one of the pic of a project where I recently added logo for tech stack !! I think this will give you idea what I am gonna do !!


![Screenshot 2021-03-12 224657](https://user-images.githubusercontent.com/76584243/111140620-8fe3c100-85a8-11eb-8acf-258dc27ec4a8.png)

**Comment by khushishikhu** [comment]
@rohank2502 Thank you for opening this issue. I liked your badges for tech stack. Assigning this to you

**Comment by rohank2502** [comment]
@khushishikhu Someone have already worked on This issue and its not fair to change that So Should I close this issue or you want my badges to get added please let me Know I will be happy to work !

**Comment by khushishikhu** [comment]
@rohank2502 if you are interested in any other badges which isn't there then please add otherwise you are free to close this issue
