### ISSUE TITLE
Adding Code of Conduct 

### ISSUE THREAD

**Issue by rohank2502** [Feminine-Divine/periodo#72]
## 📚 Documentation

I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by Aaishpra** [comment]
@rohank2502 you can work on creating code of conduct file cuz we already have a pr for contributing.md.
Ps: Change the Issue title and description if you plan on working on code of conduct.

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 you can work on creating code of conduct file cuz we already have a pr for contributing.md.
> Ps: Change the Issue title and description if you plan on working on code of conduct.

What is  exact work in code of conduct !!

**Comment by Aaishpra** [comment]
Please create a copy of [this](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) file naming code of conduct.md and add it in the .github folder also change the link of code of conduct.md in readme to the link to this file.
For further details about creating a code_of_conduct.md have a look at this [instance](https://github.com/sampart/open-source-code-of-conduct/blob/master/code_of_conduct.md)
And the email address associated with this will be 
femininedivine591@gmail.com.

**Comment by rohank2502** [comment]
Created  code_of_conduct.md have a look at it !!
