### ISSUE TITLE
Add a navbar.

### ISSUE THREAD

**Issue by padmajabhol** [Feminine-Divine/periodo#75]
## Is your feature request related to a problem? Please describe.
The page does not have a navbar.

## Describe the solution you'd like
I could add a navbar.

**Comment by khushishikhu** [comment]
@padmajabhol Can you please specify which page doesn't have navbar. Because I can see it on every page.

**Comment by khushishikhu** [comment]
@padmajabhol As all the pages have babbar so closing this issue
