### ISSUE TITLE
Contact Gynecologist Option 

### ISSUE THREAD

**Issue by AasthaNautiyal** [Feminine-Divine/periodo#76]
The above option will help user to interact with the gynecologist related to menstrual issues and seek immediate guidance.
I can work on its front end . Can you please assign it to me?

**Comment by khushishikhu** [comment]
@AasthaNautiyal  I liked this idea for implementing on the Project. Can you please give us a brief description for how you are going to implement this or just make another page for it on the website. Assigning thi to you

**Comment by AasthaNautiyal** [comment]
@khushishikhu The user would be asked for information like age, weight, date of the latest period cycle ,if they have been detected with lifestyle disorders and to describe the symptoms .
This will then be mailed to the gynecologist with all basic info already available. 
Through this the gynecologist can be contacted. I can implement it by working on its front end with html & css.
 Hope this approach is fine .Thank You.

**Comment by khushishikhu** [comment]
@AasthaNautiyal I got your concept it's really awesome. But we use Nextjs here and material UI. So make the page by keeping those things in mind you can work on the issue

**Comment by AasthaNautiyal** [comment]
![image](https://user-images.githubusercontent.com/78968859/111188019-99861c80-85da-11eb-8d94-796c8937d877.png)
@khushishikhu Hi I just made the outline of the contact gynecologist option .I need to do the styling part but are there any more options I should add to it? Please guide me .Thank you.

**Comment by khushishikhu** [comment]
@AasthaNautiyal just add one more field about how many months your Periods are late.
