### ISSUE TITLE
We can also live live locations of nearest restrooms,washrooms and hospitals in case of any emergency.

### ISSUE THREAD

**Issue by AakankshaShah** [Feminine-Divine/periodo#78]
## Describe the solution you'd like
I want to provide an additional feature of a map where a user can find washrooms and hospitals nearer to her live locations

**Comment by khushishikhu** [comment]
@AakankshaShah Please follow the issue template style for opening any issue. It is very difficult for mentors to understand the issue you are trying to convey us. we appriciate your efforts towards the project. i hope you get my Point

**Comment by Aaishpra** [comment]
@AakankshaShah any updates on this can you tell us how will you implement the map part and all the ui.

**Comment by AakankshaShah** [comment]
We can Use Google Map APIs for this.

**Comment by Aaishpra** [comment]
Okay if you're still interested then assigning you this.

**Comment by AakankshaShah** [comment]
@Aaishpra  Thank you ma'am I will try my best.

**Comment by Aaishpra** [comment]
No mam just @Aaishpra please ☺️

**Comment by vanshika2906** [comment]
Hi. Would love to work with @AakankshaShah on this issue @Aaishpra . Can you please this is to me also. Thankyou!

**Comment by khushishikhu** [comment]
@vanshika2906 assigning this to you. Happy Coding!!
