### ISSUE TITLE
coding: highlight calander

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#8]
## Description 
Highlight the calendar for next five days from the starting date of the period in same color.

**Comment by sayna3311** [comment]
I would love to contribute, please assign this to me :)

**Comment by khushishikhu** [comment]
@sayna3311 assigning this to you. Happy Coding!!

**Comment by codebuzzer01** [comment]
Hey! Do consider me for this issue.

**Comment by sayna3311** [comment]
![image](https://user-images.githubusercontent.com/67572440/110597286-5aa13280-81a6-11eb-9f2c-6230d12ca6aa.png)
First, the user selects the first date.
![image](https://user-images.githubusercontent.com/67572440/110597311-67be2180-81a6-11eb-9ffe-a75b83b818d1.png)
Then the expected end date.
![image](https://user-images.githubusercontent.com/67572440/110597358-76a4d400-81a6-11eb-8e5f-71d71336851e.png)
Also, can be reset in case the user mistakenly clicks some other day.

I have done the changes like this. 
I thought the range differs from user to user, so it would be better not to hardcode it to just 5 days, and let them select range on their own :)
Then, the next button on the right side is for going to the next page that i.e. '/flow' path.

**Comment by khushishikhu** [comment]
@sayna3311 Please Make a PR for it as well Because then only we can merge your code in our code base.

**Comment by sayna3311** [comment]
Yeah, sure! :)
