### ISSUE TITLE
coding: Create a splash screen

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#80]
**Describe the bug**
Create and design a splash screen for the project whenever we open the website.

**Additional context**
Approval of two mentors needed

**Comment by mdPial** [comment]
I would like to work on that issue. I have no pending tasks.

**Comment by khushishikhu** [comment]
@mdPial assigning this to you

**Comment by mdPial** [comment]
Do I have to make responsive too for this issue?

**Comment by mdPial** [comment]
I have made this. Am I going in right direction?.
![grab-landing-page](https://j.gifs.com/mOBlM3.gif)

**Comment by khushishikhu** [comment]
@mdPial it would be great if you can make it responsive.
But we loved how you created this splash screen 😍😍. Thank you so much. Make a PR also for this

**Comment by mdPial** [comment]
Okay I will look for good background image😊 and try to make it responsive.
