### ISSUE TITLE
Creating contact us page

### ISSUE THREAD

**Issue by WaderManasi** [Feminine-Divine/periodo#83]
## Describe the solution you'd like
Contact us page will be consisting of styled contact form.
I would like to contribute being part of gssoc'21

**Comment by Aaishpra** [comment]
Please try to follow Issue Template from next time.
@WaderManasi

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?

**Comment by khushishikhu** [comment]
@WaderManasi are you still working on this issue? or should i assign this to @ShambhaviSharma0110

**Comment by WaderManasi** [comment]
I have already created PR for the same.

**Comment by WaderManasi** [comment]
As you told not to create another PR for contact page, I have merged it into the previous PR which was created for the Footer

**Comment by khushishikhu** [comment]
@WaderManasi yes we know but are you looking for the suggestions we have suggested you on that? Please do let us know

**Comment by khushishikhu** [comment]
@WaderManasi  ya I have checked it out can you just please add the screenshot of the contact us thing you have added. I am very keen to see that🤩

**Comment by WaderManasi** [comment]
Sure...
![contaxt](https://user-images.githubusercontent.com/52437677/111861254-cdfb2f00-8972-11eb-8eba-d56511dbd1b3.PNG)

**Comment by Aaishpra** [comment]
@WaderManasi can you update your fork once and then send the screenshot, cuz the background has been changed recently.

**Comment by Aaishpra** [comment]
And may be change the white background of card to pink cuz it will look good on the recent white background.
Again thanks for your hardwork and time and sorry for so many requests, the project is still in developing state so we sometimes have to ask a lot of changes in PRs, hope you don't mind 😉

**Comment by WaderManasi** [comment]
First of all @Aaishpra, I request you to merge the contact page, coz other contributors who are willing to change theme of website can work on it!. It is not easy for me to keep on changing the things according to changes done by other people. 

I have updated my work 4 times with current upstream which has lead to many conflicts because of other contributions being merged.

I would like to tell that (**not only regarding my case**)  the PR which fullfill the requirement would be merged immediately so that other contributors are able to view the **Recent Changes** updated in their clone.

**Comment by Aaishpra** [comment]
@WaderManasi the motive of open source is not just merging PRs(and getting points here in the case of gssoc), but learning the workflow and establishing the bond with the community. I personally have submitted pull requests to many organisation and had to change my work everytime they decided they needed something new from it (in one case 22 times). Please understand that this is my project, and i am not willing to add something which can cause error to the project or a feature which won't last long.

Ps : Getting happiness or points from a lot of merged PRs won't last you long but the learning and experience you got by working on it will🤞🏻

**Comment by WaderManasi** [comment]
@Aaishpra  I have clearly mentioned that it was **NOT ONLY REGARDING MY CASE**.
My intention of saying was **not** at all regarding gssoc points 😂😂😂 .
Just saying that merge other people's PR's which are approved but still pending, so that everyone's contribution will we visible to the new contributor and would be able to make changes in them too!

**Comment by WaderManasi** [comment]
I can understand your concern regarding your project. 
As you told I have already changed the form color from white to pink💗
But just thought to share with you.

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu is it pending? If yes i am willing to work on it :)

**Comment by anushka-srivastava22** [comment]
I am gssoc participant. Can I work upon this issue . I would complete my work within few days.

**Comment by subhangi2731** [comment]
@Aaishpra please assign me these issues . I will work and share u the status

**Comment by subhangi2731** [comment]
@Aaishpra please assign me so that I can start working

**Comment by subhangi2731** [comment]
@khushishikhu I want to work on this too please assign me I will send a pr within 2 days

**Comment by khushishikhu** [comment]
@subhangi2731 Sorry but I guess this issue has been done with some other method. you can take any other issue.
