### ISSUE TITLE
spelling error in readme file

### ISSUE THREAD

**Issue by kanchi12P** [Feminine-Divine/periodo#86]
**Describe the bug**
spelling error in readme.md file
in the documentation section

instead of "contributing" it's written "contrbuting"

**Screenshots**

![Screenshot (8574)](https://user-images.githubusercontent.com/78892305/111041024-2e164080-845c-11eb-96f0-569771ade163.png)

**Additional context**
**I am gssoc'21 participant**
** I will make the changes , please assign it to me**

**Comment by Aaishpra** [comment]
@kanchi12P comment here to get assigned in the issue.

**Comment by kanchi12P** [comment]
please assign the issue

**Comment by kanchi12P** [comment]
> @kanchi12P comment here to get assigned in the issue.

Ok please assign the issue

**Comment by kanchi12P** [comment]
@Aaishpra shall I make PR

**Comment by Aaishpra** [comment]
> @Aaishpra shall I make PR

yes please

**Comment by kanchi12P** [comment]
@Aaishpra I have made pr please review it
