### ISSUE TITLE
Coding: Improvment in Navbar with responsive  

### ISSUE THREAD

**Issue by WebVishal** [Feminine-Divine/periodo#87]
Hi @khushishikhu, I think there should be some space between the logo and the navbar items in the header so that it looks good can I work on it as a Participant Gssoc'21?
!please assigned this issue to me.

**Comment by khushishikhu** [comment]
@WebVishal ohk you can work on this issue

**Comment by haarsh01** [comment]
Hello I am 'a participant of GSSoC'21
I can contribute to this issue. 
Please assign me this task
Thank you!
