### ISSUE TITLE
Reasearch: How to integrate Chat Bot feature in the website

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/periodo#9]
## Description
Add chatbot feature to the website for the convenience of users suggesting about their diets and mood swings during their Periods.

## Solution
Elaborate and clear report about features and methods which can be used for integrating Chatbot into the website

**Comment by parulsurana** [comment]
@Aaishpra, Please assign this task to me, I am selected as a Mentee at GirlScript Summer of Code and this project really excites me so I would love to contribute to such an amazing repo. :)

**Comment by Aaishpra** [comment]
Thanks for the appreciation, 🤗🤗 @parulsurana since the coding period hasn't started yet, I can't assign this issue to you right now, but do comment on 8th i will happily assign you here.

**Comment by parulsurana** [comment]
Okay Thanku :)

**Comment by parulsurana** [comment]
Hey Thank You for replying, now can i start working on it? :)

**Comment by parulsurana** [comment]
Hey @Aaishpra Thank You for replying, now can i start working on it? :)

**Comment by Ruchip16** [comment]
Can I work on this issue?

**Comment by khushishikhu** [comment]
@parulsurana  assigning this to you. Happy Coding!!

**Comment by parulsurana** [comment]
Hey! I am Implementing chatbot using app.chatBot and then I will integrate the created chatbot in the project. My progress you can see in the video which I Have linked. 
And soon I will do the PR for the same. 

https://user-images.githubusercontent.com/63437071/110968029-0a2ffd80-837d-11eb-9ebf-dc20c153bbe3.mp4

**Comment by Aaishpra** [comment]
You are on the right track keep updating😉
@parulsurana

**Comment by khushishikhu** [comment]
@parulsurana can you please make a PR for it

**Comment by parulsurana** [comment]
Yeah sure, I will do it.
Sorry for being late.

**Comment by parulsurana** [comment]
Hey! @khushishikhu and @Aaishpra I have made the PR. Please review the 2nd PR. Thanks :)
