### ISSUE TITLE
Mentioning Techstack and Open Source badges

### ISSUE THREAD

**Issue by WaderManasi** [Feminine-Divine/periodo#93]
## 📚 Documentation
Techstack used in project can be mentioned in attractive way by using github feature - github badges. Along with it, open source badges also can be added.
Eg: 
![badge](https://user-images.githubusercontent.com/52437677/111151097-038bcb00-85b5-11eb-8c4b-8ca947a637f9.PNG)
I would like to contribute for the same.

**Comment by khushishikhu** [comment]
@WaderManasi Thank you for opening this issue. Assigning this to you✌️

**Comment by WaderManasi** [comment]
Thank you assigning @khushishikhu
